// People on the move: who went where, and who they became. Each map shows the movements that happened
// between the previous map and this one. Coordinates are [longitude, latitude]; dates are approximate.
// Note: names like "Dravidian" or "Indo-Aryan" are language families, not bloodlines. Genes and languages
// often travelled together, but not always.

export const MOVES = [
  // Deep past
  { from: -70000, to: -50000, who: "Modern humans leave Africa", became: "Ancestors of everyone outside Africa", tag: "Everyone outside Africa",
    note: "A small group crossed from East Africa into Arabia. Every person whose family comes from outside Africa descends from them.",
    paths: [[[37, 6], [42, 11], [43.5, 12.6], [48, 15], [55, 20], [58, 24]]] },
  { from: -65000, to: -50000, who: "Coastal travellers", became: "First Indians",
    note: "Scientists call them the Ancient Ancestral South Indians. Their DNA is in almost everyone in South Asia today, most of all in the south and among tribal peoples.",
    paths: [[[58, 24], [63, 25], [67, 24], [72, 21], [76, 14], [78, 10]]] },
  { from: -65000, to: -50000, who: "Sea-crossers through Southeast Asia", became: "Aboriginal Australians and Papuans", tag: "Aboriginal Australians, Papuans",
    note: "They crossed open sea to reach New Guinea and Australia, which were one land then. Aboriginal Australians are one of the oldest continuous cultures on Earth.",
    paths: [[[80, 13], [92, 18], [98, 10], [104, 1], [111, -6], [122, -9], [131, -13], [134, -23]]] },
  { from: -45000, to: -40000, who: "Modern humans into Europe", became: "Europe's hunter-gatherers",
    note: "They met the Neanderthals already living there and had children with some of them. They painted the caves of Chauvet and Lascaux.",
    paths: [[[35.5, 33], [36, 37], [29, 40], [22, 43], [14, 46], [3, 47]]] },
  { from: -45000, to: -40000, who: "Modern humans across Asia", became: "Ancestors of East Asians", tag: "East Asians’ ancestors",
    note: "They spread across Central and East Asia, meeting and mixing with Denisovans on the way.",
    paths: [[[62, 37], [75, 40], [90, 40], [105, 36], [116, 38]]] },
  { from: -20000, to: -13000, who: "Siberian hunters", became: "The first Americans",
    note: "They crossed the Bering land bridge, which joined Asia and Alaska when sea levels were low, then spread down to Chile in a few thousand years.",
    paths: [[[128, 44], [140, 52], [155, 60], [172, 66], [-170, 66], [-158, 63], [-138, 59], [-125, 50], [-112, 36], [-100, 22], [-82, 8], [-76, -10], [-72, -41]]] },

  // Farming changes everything
  { from: -8000, to: -4000, who: "Farmers and herders from the Iranian plateau", became: "Indus Valley people",
    note: "They moved east and mixed with the First Indians. That mix became the main ancestry of the Indus Valley (Harappan) civilisation.",
    paths: [[[50, 34], [55, 31], [60, 29], [65, 28], [69, 27]]] },
  { from: -7000, to: -4000, who: "Farmers from Anatolia (Turkey)", became: "Europe's first farmers",
    note: "They brought wheat, barley and sheep into Europe and mixed with the hunter-gatherers already there.",
    paths: [[[33, 38], [27, 41], [22, 43], [18, 46], [12, 49], [5, 51], [-2, 53]]] },
  { from: -3000, to: -2500, who: "Steppe herders (Yamnaya)", became: "Most Europeans today",
    note: "Horse-riding herders from today's Ukraine and Russia moved west. Most Europeans are a mix of them, the first farmers and the hunter-gatherers. They probably spread the Indo-European languages.",
    paths: [[[45, 48], [38, 48], [30, 49], [22, 51], [14, 52], [6, 52]]] },
  { from: -3000, to: 1000, who: "Bantu-speaking farmers", became: "Bantu peoples (Swahili, Zulu, Kikuyu…)", tag: "Bantu peoples",
    note: "From today's Nigeria and Cameroon they spread over central, eastern and southern Africa with crops, cattle and later iron. The Khoisan, who had lived in the south far longer, were pushed into drier lands or absorbed.",
    paths: [[[11, 5], [18, 2], [26, 0], [32, -3], [35, -10], [33, -18], [29, -27]], [[12, 4], [14, -3], [16, -10], [18, -17]]] },
  { from: -3000, to: -1000, who: "Austronesians from Taiwan", became: "Filipinos, Indonesians and Malays", tag: "Filipinos, Malays, Indonesians",
    note: "Rice-farming seafarers sailed south from Taiwan. Their languages (Tagalog, Malay, Javanese…) all come from one ancestor.",
    paths: [[[121, 23.5], [121, 16], [123, 8], [118, 2], [110, -4]]] },
  { from: -2500, to: -1000, who: "Austroasiatic speakers from Southeast Asia", became: "Munda peoples of India (Santal, Ho)", tag: "Munda peoples", side: "right", dy: 16,
    note: "Their languages are cousins of Khmer and Vietnamese, not of Hindi or Tamil.",
    paths: [[[102, 18], [96, 22], [91, 24], [86, 23]]] },

  // India takes shape
  { from: -2000, to: -1500, who: "Steppe herders", became: "Ancestral North Indians",
    note: "They came through Central Asia into the northwest and mixed with the people there. They brought Indo-Aryan languages: the ancestor of Sanskrit, and later Hindi, Bengali, Marathi, Punjabi.",
    paths: [[[62, 46], [65, 41], [68, 37], [71, 33], [75, 30], [78, 28]]] },
  { from: -1900, to: -1000, who: "Indus-related peoples, after the cities declined", became: "Ancestral South Indians",
    note: "They moved south and east and mixed further with the First Indians. Many linguists think they spoke early Dravidian languages, the family of Tamil, Telugu, Kannada and Malayalam, but that is still debated. Today almost every Indian is a mix of North and South ancestry, in different amounts.",
    paths: [[[69, 27], [73, 22], [76, 17], [78, 13], [78, 9]]] },
  { from: -1000, to: 300, who: "Rice farmers from Korea (Yayoi)", became: "The Japanese",
    note: "They mixed with the Jōmon hunter-gatherers already living in Japan.",
    paths: [[[127, 37], [129, 35], [131, 33.5], [135, 34.7]]] },
  { from: -1000, to: 1300, who: "Austronesian sailors", became: "Polynesians (Samoans, Hawaiians, Māori)", tag: "Polynesians",
    note: "In outrigger canoes, navigating by stars and swells, they settled the Pacific: Samoa by ~800 BC, Hawai'i by ~AD 1000, New Zealand by ~1280.",
    paths: [[[150, -5], [165, -14], [178, -17], [-172, -14], [-160, -17], [-155, 19]], [[-160, -17], [175, -38]]] },

  // The first millennium AD
  { from: 300, to: 700, who: "Austronesian sailors from Borneo", became: "The Malagasy",
    note: "They crossed the whole Indian Ocean. Malagasy is still closest to a language spoken in Borneo, with added African ancestry and words.",
    paths: [[[114, 0], [100, -5], [80, -10], [60, -15], [47, -19]]] },
  { from: 400, to: 600, who: "Angles, Saxons and Jutes", became: "The English",
    note: "Germanic peoples from Denmark and northern Germany settled in Britain after the Romans left. Their language became English.",
    paths: [[[9.5, 55], [6, 54], [2, 53], [-1, 52.5]]] },
  { from: 500, to: 700, who: "Slavs", became: "Slavic peoples (Poles, Serbs, Russians…)", tag: "Slavic peoples",
    note: "From around today's Ukraine and Belarus they spread west, south into the Balkans and east.",
    paths: [[[28, 52], [22, 47], [20, 44]], [[28, 52], [20, 52]], [[28, 52], [38, 56]]] },
  { from: 550, to: 1100, who: "Turkic peoples from Central Asia", became: "Turks, Azerbaijanis, Uzbeks…", tag: "Turkic peoples",
    note: "Turkic-speaking herders moved west across the steppe. The Seljuks reached Anatolia after 1071, and it slowly became Turkish-speaking.",
    paths: [[[95, 47], [80, 45], [65, 41], [52, 38], [40, 39], [32, 39]]] },
  { from: 632, to: 750, who: "Arab armies and settlers", became: "The Arabic-speaking world",
    note: "After the rise of Islam, Arabic spread from Arabia across the Middle East and North Africa. Most people there are descended from those who already lived there, and switched language and religion.",
    paths: [[[39.8, 21.4], [36, 30], [31, 30], [20, 31], [10, 34], [-5, 34]]] },
  { from: 600, to: 1300, who: "Romani ancestors from northwest India", became: "The Romani of Europe",
    note: "They left the area of Rajasthan and Punjab around AD 500 to 1000. Romani is still an Indian language, a cousin of Hindi and Punjabi.",
    paths: [[[74, 29], [62, 32], [50, 35], [40, 38], [29, 41], [22, 44]]] },
  { from: 700, to: 1000, who: "Zoroastrians from Iran", became: "The Parsis of India",
    note: "Leaving Persia after the Arab conquest, they landed in Gujarat (Sanjan). Later many moved to Bombay.",
    paths: [[[52, 32], [57, 27], [63, 24], [69, 22], [72.8, 20.2]]] },
  { from: 790, to: 1050, who: "Norse (Vikings)", became: "Icelanders and Normans",
    note: "Norse seafarers raided, traded and settled from Iceland to Normandy and Kyiv.",
    paths: [[[10, 60], [0, 61], [-10, 63], [-21, 64]], [[8, 57], [2, 53], [0, 49.5]]] },
  { from: 850, to: 900, who: "Magyars", became: "Hungarians",
    note: "Horse riders from the Ural region settled the Carpathian basin in 895. Hungarian is a cousin of Finnish, not of its neighbours.",
    paths: [[[56, 54], [45, 50], [35, 48], [19, 47]]] },

  // The modern world
  { from: 1500, to: 1866, who: "Enslaved Africans, taken by force", became: "The African diaspora of the Americas", tag: "African diaspora",
    note: "About 12.5 million people were shipped across the Atlantic; nearly 2 million died on the way. Their descendants live across Brazil, the Caribbean and the USA.",
    paths: [[[3, 6], [-15, 3], [-30, -3], [-38.5, -12.9]], [[3, 6], [-20, 12], [-45, 17], [-61, 15], [-76, 18]]] },
  { from: 1500, to: 1914, who: "European settlers", became: "Most people of the Americas, Australia and New Zealand", tag: "New nations of settlers",
    note: "Tens of millions crossed the oceans. In Latin America most people today are a mix of Native American, European and African ancestry.",
    paths: [[[-8, 42], [-30, 38], [-55, 32], [-74, 40.7]], [[-6, 37], [-30, 15], [-45, -10], [-58, -34]], [[-2, 50], [-20, 10], [20, -38], [100, -40], [151, -34]]] },
  { from: 1838, to: 1917, who: "Indian indentured labourers", became: "Indo-Trinidadians, Indo-Guyanese, Indo-Fijians, Indo-Mauritians", tag: "Indo-Caribbeans, Indo-Fijians…",
    note: "After slavery ended, about 1.3 million Indians, mostly from Bihar, Uttar Pradesh and Tamil Nadu, signed five-year contracts to work on sugar plantations. Most stayed. Today about 40% of Trinidad and Guyana are of Indian descent.",
    paths: [[[88.3, 22.5], [82, 5], [65, -15], [57.5, -20.2]], [[80.3, 13], [65, -20], [30, -38], [0, -25], [-35, -2], [-61.3, 10.6]], [[88.3, 22.5], [105, -10], [150, -22], [178, -18]]] },
  { from: 1840, to: 1930, who: "Chinese emigrants", became: "Chinese communities of Southeast Asia", tag: "Chinese diaspora",
    note: "Mostly from Fujian and Guangdong, they went to work and trade in Malaya, Singapore, Indonesia and beyond. About three in four Singaporeans are of Chinese descent.",
    paths: [[[116.7, 23.4], [110, 13], [103.8, 1.3]]] },
  { from: 1845, to: 1855, who: "Irish fleeing the Great Famine", became: "Irish Americans",
    note: "About a million died and more than a million left. Ireland's population still hasn't recovered to its 1840 level.",
    paths: [[[-8, 53], [-30, 50], [-55, 45], [-74, 40.7]]] },
  { from: 1947, to: 1947, who: "Partition of India", became: "Some 15 million cross the new borders", tag: "Partition: 15 million moved",
    note: "Hindus and Sikhs moved to India, and Muslims to Pakistan, East and West. Up to a million or more were killed. It was one of the largest migrations in history.",
    paths: [[[72, 31], [76.5, 30]], [[77, 28.6], [72.5, 30.6]], [[88.4, 22.6], [90.4, 23.8]], [[90, 24.2], [88, 23]]] },
  { from: 1970, to: 2010, who: "South Asian workers", became: "Over half the people of the Gulf states", tag: "Gulf workers",
    note: "Millions from Kerala, Pakistan, Bangladesh and Nepal went to work in the Gulf. Kerala's economy runs partly on the money they send home.",
    paths: [[[76.3, 10], [65, 17], [55.3, 25.2]], [[73, 31], [62, 26], [55.3, 25.2]]] },
];
