// Ready-made recaps so visitors can see what the app does before adding an API key.
// All three books are in the public domain.
export const DEMOS = [
  {
    id: "demo-pride",
    input: { title: "Pride and Prejudice", author: "Jane Austen", format: "book", page: 150, total: 416, context: "Charlotte Lucas just agreed to marry Mr Collins." },
    result: {
      known: true, caution: "",
      title: "Pride and Prejudice", author: "Jane Austen", style: "scrapbook",
      recap: "The Bennets of Longbourn have five unmarried daughters and a house that can't pass to any of them. When wealthy Mr Bingley rents nearby Netherfield, Mrs Bennet sees a husband for Jane. Elizabeth, meanwhile, has taken a firm dislike to his proud friend Mr Darcy.",
      you_are_here: "Charlotte Lucas, Elizabeth's sensible friend, has just accepted Mr Collins, three days after Elizabeth turned him down.",
      beats: [
        { marker: "Ch. 1–3", emoji: "💃", title: "The Meryton assembly", text: "Bingley is charming and dances twice with Jane. Darcy refuses to dance and calls Elizabeth \"tolerable; but not handsome enough to tempt me\". She overhears and turns it into a funny story." },
        { marker: "Ch. 6", emoji: "👀", title: "Fine eyes", text: "Darcy, against his own judgement, starts noticing how intelligent Elizabeth's dark eyes make her face. Elizabeth has no idea." },
        { marker: "Ch. 7–12", emoji: "🌧️", title: "A cold at Netherfield", text: "Mrs Bennet sends Jane to Netherfield on horseback in the rain. Jane falls ill and has to stay. Elizabeth walks three muddy miles to nurse her, trades barbs with Darcy, and fends off Caroline Bingley's sniping." },
        { marker: "Ch. 13–15", emoji: "📜", title: "Enter Mr Collins", text: "The cousin who will inherit Longbourn arrives: pompous, long-winded, and devoted to his patroness Lady Catherine de Bourgh. He means to marry one of the Bennet girls." },
        { marker: "Ch. 15–16", emoji: "🎖️", title: "A charming officer", text: "Mr Wickham joins the militia in Meryton. He tells Elizabeth that Darcy denied him a church living Darcy's late father had promised him. Elizabeth believes every word. Jane suspects a misunderstanding." },
        { marker: "Ch. 18", emoji: "🎻", title: "The Netherfield ball", text: "Wickham doesn't come. Elizabeth dances with Darcy and they quarrel politely about Wickham. Her family embarrasses her all evening: Mrs Bennet boasts about Jane and Bingley, Mary sings too long, and Mr Collins introduces himself to Darcy uninvited." },
        { marker: "Ch. 19–20", emoji: "💍", title: "A proposal, refused", text: "Mr Collins proposes to Elizabeth and refuses to believe her no. Mrs Bennet is furious. Mr Bennet says she will never see her mother again if she marries him, and never see him again if she doesn't." },
        { marker: "Ch. 21", emoji: "✉️", title: "Netherfield empties", text: "The whole Bingley party leaves for London. Caroline writes to Jane that they won't be back this winter and hints that Bingley admires Darcy's sister. Jane is heartbroken; Elizabeth suspects Caroline." },
      ],
      cast: [
        { name: "Elizabeth Bennet", symbol: "Eb", emoji: "📚", role: "Second daughter. Quick-witted, laughs at folly, and dislikes Mr Darcy." },
        { name: "Jane Bennet", symbol: "Jb", emoji: "🌸", role: "The eldest. Gentle, thinks well of everyone, and fond of Mr Bingley." },
        { name: "Mr Darcy", symbol: "Fd", emoji: "🎩", role: "Bingley's rich, reserved friend from Derbyshire. Everyone in Meryton finds him proud." },
        { name: "Mr Bingley", symbol: "Cb", emoji: "🙂", role: "Amiable new tenant of Netherfield, now gone to London." },
        { name: "Mr Wickham", symbol: "Gw", emoji: "🎖️", role: "Handsome militia officer who says Darcy cheated him." },
        { name: "Mr Collins", symbol: "Wc", emoji: "⛪", role: "Clergyman cousin who will inherit Longbourn. Now engaged to Charlotte." },
        { name: "Charlotte Lucas", symbol: "Cl", emoji: "☕", role: "Elizabeth's practical friend, 27, who wants a secure home." },
        { name: "Mrs Bennet", symbol: "Mb", emoji: "🗣️", role: "Mother on a mission to marry off her daughters. Her nerves are famous." },
      ],
      remember: [
        "Longbourn is entailed: it passes to Mr Collins, not to any Bennet daughter.",
        "Lady Catherine de Bourgh, Mr Collins's patroness, is also Darcy's aunt (Wickham mentioned it).",
        "Mr Bennet is on Elizabeth's side about Mr Collins.",
      ],
    },
  },
  {
    id: "demo-80-days",
    input: { title: "Around the World in Eighty Days", author: "Jules Verne", format: "audio", percent: 51, context: "Fix just got Passepartout drugged in an opium den in Hong Kong." },
    result: {
      known: true, caution: "",
      title: "Around the World in Eighty Days", author: "Jules Verne", style: "journey",
      recap: "Phileas Fogg, the most precise man in London, bets £20,000 that he can circle the globe in eighty days, and leaves that same evening. Behind him trails Detective Fix, convinced Fogg is a bank robber on the run.",
      you_are_here: "In Hong Kong, Fix has just drugged Passepartout so he can't tell Fogg that the steamer Carnatic is leaving tonight instead of tomorrow morning.",
      beats: [
        { marker: "London", emoji: "🎩", title: "The wager", text: "On 2 October 1872, Fogg hires a French valet, Passepartout, then bets his Reform Club friends £20,000 that he can go round the world in 80 days. He leaves on the 8:45 pm train." },
        { marker: "Suez", emoji: "🔍", title: "A detective takes an interest", text: "Detective Fix decides Fogg matches the description of the man who robbed the Bank of England of £55,000. Without an arrest warrant, he follows him and befriends Passepartout." },
        { marker: "Bombay", emoji: "👞", title: "Shoes in the temple", text: "Passepartout wanders into a temple without removing his shoes. Priests attack him and he only just escapes. Fix makes a note of it." },
        { marker: "Kholby", emoji: "🐘", title: "The railway runs out", text: "The Great Indian Peninsula line isn't finished: fifty miles of jungle are missing. Fogg buys an elephant called Kiouni for £2,000 and pushes on with Sir Francis Cromarty and a Parsi guide." },
        { marker: "The forest", emoji: "🔥", title: "The rescue of Aouda", text: "They come across a procession preparing to burn a young widow, Aouda, on her husband's pyre. Fogg decides to save her. Passepartout takes the dead rajah's place and carries her off." },
        { marker: "Calcutta", emoji: "⚖️", title: "Court and bail", text: "Fix has the temple priests bring a charge. Fogg pays £2,000 bail, walks out, and boards the Rangoon for Hong Kong with Aouda." },
        { marker: "Hong Kong", emoji: "🚢", title: "Fix shows his hand", text: "Aouda's relative turns out to have left for Europe, so Fogg will take her with him. Fix tells Passepartout he's a detective and asks for his help. Passepartout loyally refuses, so Fix turns to opium." },
      ],
      cast: [
        { name: "Phileas Fogg", symbol: "Pf", emoji: "🎩", role: "Unflappable English gentleman who lives by the clock." },
        { name: "Passepartout", symbol: "Pa", emoji: "🧳", role: "Fogg's good-hearted French valet; ex-acrobat, ex-fireman." },
        { name: "Detective Fix", symbol: "Fx", emoji: "🔍", role: "Scotland Yard detective sure that Fogg is the bank robber." },
        { name: "Aouda", symbol: "Ao", emoji: "✨", role: "Young widow Fogg rescued in India, now travelling with them." },
        { name: "Sir Francis Cromarty", symbol: "Fc", emoji: "🎖️", role: "Brigadier-general who rode the elephant with them and left them at Allahabad." },
      ],
      remember: [
        "Deadline: back at the Reform Club by 8:45 pm on Saturday 21 December 1872.",
        "The Bank of England robbery was £55,000; Fix is chasing the reward.",
        "Fogg has been spending lavishly from a large bag of banknotes.",
      ],
    },
  },
  {
    id: "demo-frankenstein",
    input: { title: "Frankenstein", author: "Mary Shelley", format: "ebook", page: 60, total: 220, context: "Victor just got the letter saying his little brother William has been murdered." },
    result: {
      known: true, caution: "",
      title: "Frankenstein", author: "Mary Shelley", style: "lab",
      recap: "On an Arctic expedition, Captain Walton pulls a half-frozen stranger from the ice: Victor Frankenstein. Victor tells him how a boyhood passion for science led him to build and bring to life a creature, and how he fled the moment it opened its eyes.",
      you_are_here: "Victor, recovered from months of fever, has just read his father's letter: his youngest brother William has been found murdered near Geneva.",
      beats: [
        { marker: "Exp. 01", emoji: "🧊", title: "Letters from the ice", text: "Robert Walton writes to his sister from a ship trapped in Arctic ice. The crew rescue a gaunt stranger who was chasing something across the ice by sledge. The stranger begins his story." },
        { marker: "Exp. 02", emoji: "🏡", title: "A Geneva childhood", text: "Victor grows up adored, with Elizabeth Lavenza, adopted into the family as his \"more than sister\", and his best friend Henry Clerval. He devours old alchemists like Cornelius Agrippa, and watches lightning blast an oak to splinters." },
        { marker: "Exp. 03", emoji: "🕯️", title: "A mother's last wish", text: "His mother catches scarlet fever while nursing Elizabeth and dies, hoping Victor and Elizabeth will marry. Soon after, Victor leaves for university." },
        { marker: "Exp. 04", emoji: "⚗️", title: "Ingolstadt obsession", text: "Inspired by Professor Waldman, Victor finds the secret of giving life to lifeless matter. He works in secret for two years, cutting himself off from everyone, assembling a body of gigantic size." },
        { marker: "Exp. 05", emoji: "⚡", title: "A dreary night of November", text: "The creature opens a dull yellow eye. Horrified by what he has made, Victor flees. It finds him at his bedside, and he runs into the streets." },
        { marker: "Exp. 06", emoji: "🩺", title: "Clerval to the rescue", text: "Henry Clerval arrives just in time. Victor collapses into a nervous fever that lasts months, and Henry nurses him through it." },
        { marker: "Exp. 07", emoji: "✉️", title: "Spring, then a letter", text: "Recovered, Victor studies languages with Henry and enjoys a walking tour. Then a letter arrives from his father." },
      ],
      cast: [
        { name: "Victor Frankenstein", symbol: "Vf", emoji: "🧪", role: "Gifted, obsessive scientist, telling his story to Walton." },
        { name: "The creature", symbol: "Cr", emoji: "⚡", role: "The gigantic being Victor brought to life and abandoned. Where it went is unknown." },
        { name: "Elizabeth Lavenza", symbol: "El", emoji: "🌼", role: "Raised with Victor; his mother hoped they would marry." },
        { name: "Henry Clerval", symbol: "Hc", emoji: "📖", role: "Victor's warm, loyal best friend; nursed him through his fever." },
        { name: "Robert Walton", symbol: "Rw", emoji: "🧭", role: "Ambitious Arctic explorer who rescued Victor and is writing it all down." },
        { name: "Alphonse Frankenstein", symbol: "Af", emoji: "🏛️", role: "Victor's kind, respected father in Geneva." },
        { name: "William Frankenstein", symbol: "Wf", emoji: "🧒", role: "Victor's youngest brother, just reported murdered." },
        { name: "Justine Moritz", symbol: "Jm", emoji: "🧺", role: "Beloved family servant, praised in Elizabeth's letter." },
      ],
      remember: [
        "Everything is told by Victor to Walton, who writes it in letters to his sister.",
        "No one but Victor knows the creature exists.",
        "Victor hasn't seen the creature since the night he fled his rooms.",
      ],
    },
  },
];
