// A typical girl's and boy's name in each country, and where names there come from.
// tone: skin tone for the little cartoon (1 lightest to 5 darkest). Written for My Roamin' Empire.
export const NAMES = {"ad":{"boy":{"first":"Marc","last":"Garcia","say":"MARK gar-SEE-uh"},
"girl":{"first":"Laia","last":"Martí","say":"LYE-uh mar-TEE"},
"about":"Andorra's official language is Catalan, so Catalan forms like Marc and Laia (a pet form of Eulàlia) are favourites. As in Spain, people officially carry two surnames, father's then mother's. García and Martí are among the most widespread family names.","tone":1},
"ae":{"boy":{"first":"Mohammed","last":"Al Mansoori","say":"moh-HAM-ed al man-SOO-ree"},
"girl":{"first":"Fatima","last":"Al Ali","say":"FAH-tee-mah al AH-lee"},
"about":"Emirati names honour the Prophet Mohammed and his daughter Fatima. 'Al' surnames point to a tribe or family, such as the Al Mansoori. A full name often strings together your own name, 'bin' (son of) or 'bint' (daughter of), your father's name, and the family name.","tone":3},
"af":{"boy":{"first":"Ahmad","last":"Ahmadi","say":"AH-mad ah-MAH-dee"},
"girl":{"first":"Zahra","last":"Rahimi","say":"ZAH-rah rah-HEE-mee"},
"about":"Many Afghans traditionally went by a single name, and surnames only spread in the 20th century. Endings like -i mean 'of' or 'belonging to', while Pashtun tribal names often end in -zai, 'son of'. Zahra, 'radiant', is a beloved name linked to the Prophet's daughter Fatima.","tone":3},
"ag":{"boy":{"first":"Joshua","last":"Joseph","say":"JOSH-oo-uh JOH-sef"},
"girl":{"first":"Aaliyah","last":"Thomas","say":"ah-LEE-yah TOM-us"},
"about":"Antiguans mostly have English first names and surnames, a legacy of British colonial rule and plantation records. Biblical-sounding surnames like Joseph and Thomas are very common, and Caribbean parents love modern, stylish first names such as Aaliyah.","tone":4},
"al":{"boy":{"first":"Ardit","last":"Hoxha","say":"AR-deet HOJ-ah"},
"girl":{"first":"Klea","last":"Shehu","say":"KLEH-ah SHEH-hoo"},
"about":"Albanian parents often choose native names: Ardit roughly means 'golden day'. Common surnames like Hoxha (an Islamic teacher) and Shehu (a sheikh) come from Ottoman-era titles. Official papers traditionally list a person's father's first name between given name and surname.","tone":1},
"am":{"boy":{"first":"Davit","last":"Grigoryan","say":"dah-VEET gree-gor-YAHN"},
"girl":{"first":"Ani","last":"Hovhannisyan","say":"ah-NEE hov-hah-nee-SYAHN"},
"about":"Most Armenian surnames end in -yan or -ian, meaning 'descendant of', so Grigoryan is 'son of Grigor' and Hovhannisyan 'son of Hovhannes' (John). Ani is named after a medieval Armenian capital, and Davit honours King David.","tone":2},
"ao":{"boy":{"first":"João","last":"Domingos","say":"zhoo-OW doh-MEEN-goosh"},
"girl":{"first":"Ana","last":"Fernandes","say":"AH-nuh fer-NAHN-desh"},
"about":"Angolans mostly use Portuguese first names and surnames from the colonial and Catholic tradition, and a Christian first name like Domingos ('of Sunday', or 'of the Lord') often became a family name. Many families also give names in Kimbundu, Umbundu or Kikongo.","tone":5},
"ar":{"boy":{"first":"Santiago","last":"González","say":"san-tee-AH-go gon-SAH-les"},
"girl":{"first":"Sofía","last":"Rodríguez","say":"so-FEE-ah rod-REE-ges"},
"about":"González ('son of Gonzalo') and Rodríguez ('son of Rodrigo') are the top Argentine surnames, both Spanish patronymics. Argentines can carry both parents' surnames but usually use just the father's day to day. Many families also have Italian surnames from big waves of migration.","tone":2},
"at":{"boy":{"first":"Lukas","last":"Gruber","say":"LOO-kahs GROO-ber"},
"girl":{"first":"Anna","last":"Huber","say":"AH-nah HOO-ber"},
"about":"Austria's most common surnames are rural. Gruber was someone who lived in a hollow or pit (Grube), and Huber held a Hube, a farmstead of a certain size. Lukas and Anna are classic, saint-inspired names that have stayed popular for decades.","tone":1},
"au":{"boy":{"first":"Jack","last":"Smith","say":"JAK SMITH"},
"girl":{"first":"Olivia","last":"Jones","say":"oh-LIV-ee-uh JOHNZ"},
"about":"Australia's top surnames, Smith (a metalworker) and Jones ('son of John', Welsh), came with British and Irish settlers. Today the country is very multicultural, so names like Nguyen, Singh and Chen are also common. Jack and Olivia regularly top the baby-name charts.","tone":1},
"az":{"boy":{"first":"Ali","last":"Mammadov","say":"ah-LEE mah-MAH-dov"},
"girl":{"first":"Leyla","last":"Aliyeva","say":"LAY-lah ah-LEE-yeh-vah"},
"about":"Mammad is the Azerbaijani form of Muhammad, and Mammadov is the country's most common surname. The Russian-style -ov/-ova endings date from Russian and Soviet rule; some families now prefer local endings like -li or -zade. Leyla, 'night', is a classic from Persian and Arabic poetry.","tone":2},
"ba":{"boy":{"first":"Amar","last":"Hodžić","say":"AH-mar HOD-jeech"},
"girl":{"first":"Lejla","last":"Hadžić","say":"LAY-lah HAD-jeech"},
"about":"Bosnian surnames usually end in -ić, a little-or-son-of ending. Hodžić comes from hodža, an Islamic teacher, and Hadžić from hadži, someone who made the pilgrimage to Mecca. Names often hint at whether a family is Bosniak, Serb or Croat. Amar and Lejla are favourite Bosniak names.","tone":1},
"bb":{"boy":{"first":"Jaden","last":"Griffith","say":"JAY-den GRIF-ith"},
"girl":{"first":"Kayla","last":"Clarke","say":"KAY-lah KLARK"},
"about":"Bajan surnames are mostly English, Welsh and Scottish, inherited through the island's long British colonial history: Griffith is Welsh, Clarke meant a clerk or scholar. First names follow modern Caribbean and American trends, with Jaden and Kayla very popular.","tone":4},
"bd":{"boy":{"first":"Sakib","last":"Hasan","say":"SHAH-kib HAH-sun"},
"girl":{"first":"Nusrat","last":"Akter","say":"NOOSH-rot AK-ter"},
"about":"Bangladeshi names mix Arabic, Persian and Bengali roots. Many men add 'Md' (Mohammad) to their official name. Surnames are flexible: siblings may have different ones, and Akter (from Arabic for 'star') is so common for women that it works almost like a title. Hasan means 'handsome, good'.","tone":4},
"be":{"boy":{"first":"Lucas","last":"Peeters","say":"LOO-kas PAY-ters"},
"girl":{"first":"Emma","last":"Janssens","say":"EM-ah YAHN-sens"},
"about":"Belgium's most common surnames are Flemish patronymics: Peeters means 'son of Peter' and Janssens 'son of Jan'. In French-speaking Wallonia, names like Dubois are more typical. Since 2014 parents can give a child the father's, mother's or both surnames.","tone":1},
"bf":{"boy":{"first":"Ibrahim","last":"Ouédraogo","say":"ib-rah-HEEM WED-rah-oh-go"},
"girl":{"first":"Aminata","last":"Sawadogo","say":"ah-mee-NAH-tah sah-wah-DOH-go"},
"about":"Ouédraogo, the most common surname, is the name of the legendary founder of the Mossi kingdoms, son of the warrior princess Yennenga; it means 'stallion'. Sawadogo is another big Mossi name. First names are often Muslim (Ibrahim, Aminata) or Christian.","tone":5},
"bg":{"boy":{"first":"Georgi","last":"Ivanov","say":"geh-OR-gee ee-VAH-nov"},
"girl":{"first":"Maria","last":"Ivanova","say":"mah-REE-ah ee-VAH-noh-vah"},
"about":"Bulgarians carry three names: a given name, a patronymic from the father's first name, and a family name. Ivanov ('son of Ivan') takes -a for women, so a sister is Ivanova. Children are often named after a grandparent, keeping names like Georgi and Maria in steady use.","tone":1},
"bh":{"boy":{"first":"Hussain","last":"Ali","say":"hoo-SAYN AH-lee"},
"girl":{"first":"Fatima","last":"Ahmed","say":"FAH-tee-mah AH-med"},
"about":"Many Bahrainis build their name as given name, then father's name, then grandfather's or family name, so 'Ali' or 'Ahmed' at the end may be a father's name. Families may also carry an 'Al' tribal or clan name. Hussain honours the Prophet's grandson.","tone":3},
"bi":{"boy":{"first":"Eric","last":"Ndayishimiye","say":"AIR-ik n-dah-yee-shee-MEE-yeh"},
"girl":{"first":"Aline","last":"Niyonkuru","say":"ah-LEEN nee-yohn-KOO-roo"},
"about":"In Burundi the Kirundi name is personal, not a family name, so siblings often have different ones. These names frequently carry faith or feeling: Ndayishimiye means 'I thank Him (God)'. A French or Christian name like Eric or Aline is usually given alongside.","tone":5},
"bj":{"boy":{"first":"Jean","last":"Houngbo","say":"ZHAHN HOONG-bo"},
"girl":{"first":"Grâce","last":"Dossou","say":"GRAHSS DOH-soo"},
"about":"Beninese often pair a French first name with a family name from Fon, Yoruba or other local languages. Fon names can record birth circumstances: Dossou is traditionally given to a boy born after twins, and has become a common surname.","tone":5},
"bn":{"boy":{"first":"Haziq","last":"bin Abdullah","say":"HAH-zik bin ab-DUL-lah"},
"girl":{"first":"Aisyah","last":"binti Ahmad","say":"AY-shah BIN-tee AH-mad"},
"about":"Bruneian Malays traditionally have no family surname. A child takes their own name plus 'bin' (son of) or 'binti' (daughter of) and the father's name, and is addressed by the first name. Abdullah means 'servant of God'; Aisyah is the Malay form of Aisha.","tone":3},
"bo":{"boy":{"first":"Santiago","last":"Mamani","say":"san-tee-AH-go mah-MAH-nee"},
"girl":{"first":"Valeria","last":"Quispe","say":"vah-LEH-ree-ah KEES-peh"},
"about":"Bolivia's most common surnames are Indigenous: Mamani is Aymara for 'falcon', and Quispe comes from Quechua. Bolivians use two surnames, father's then mother's, and Spanish first names dominate. Bolivia has one of the largest Indigenous shares of any country in the Americas.","tone":3},
"br":{"boy":{"first":"Miguel","last":"Silva","say":"mee-GEL SEEL-vah"},
"girl":{"first":"Helena","last":"Santos","say":"eh-LEH-nah SAHN-toosh"},
"about":"Silva ('forest' in Latin) and Santos ('saints') are Brazil's top surnames. Brazilians often carry several surnames, usually the mother's followed by the father's, and the last one is used formally. Miguel and Helena have topped recent baby-name lists.","tone":3},
"bs":{"boy":{"first":"Javon","last":"Rolle","say":"jah-VON ROHL"},
"girl":{"first":"Destiny","last":"Ferguson","say":"DES-tin-ee FER-gus-un"},
"about":"Rolle is especially Bahamian, linked to Lord John Rolle, whose Exuma plantations passed to the people formerly enslaved there, many of whom took his name. Ferguson reflects Scottish roots. Bahamians love inventive, upbeat first names like Destiny.","tone":4},
"bt":{"boy":{"first":"Sonam","last":"Dorji","say":"SOH-nam DOR-jee"},
"girl":{"first":"Pema","last":"Choden","say":"PEM-ah CHOH-den"},
"about":"Bhutanese have no family names: both parts are given names, often chosen by a lama, and most work for either gender. They come from Buddhist vocabulary: Dorji is the thunderbolt (vajra), Pema means 'lotus', and Sonam means 'merit' or good fortune. Siblings rarely share a name.","tone":3},
"by":{"boy":{"first":"Maksim","last":"Kovalenko","say":"mak-SEEM ko-vah-LEN-ko"},
"girl":{"first":"Darya","last":"Novik","say":"DAR-yah NO-vik"},
"about":"Belarusians use a given name, a patronymic from the father's name, and a surname. Kovalenko comes from koval, 'blacksmith', and Novik meant a newcomer. Endings like -enka, -ich and -ski are typical. Russian and Belarusian spellings of names often appear side by side.","tone":1},
"bz":{"boy":{"first":"Gabriel","last":"Garcia","say":"gah-bree-EL gar-SEE-ah"},
"girl":{"first":"Ashley","last":"Young","say":"ASH-lee YUNG"},
"about":"Belize mixes Mestizo, Creole, Maya, Garifuna and Mennonite communities, so names come in Spanish (Garcia), English (Young), Mayan and German forms. English is the official language, and many families switch easily between Spanish and English names.","tone":3},
"ca":{"boy":{"first":"Liam","last":"Smith","say":"LEE-um SMITH"},
"girl":{"first":"Olivia","last":"Tremblay","say":"oh-LIV-ee-uh trahm-BLAY"},
"about":"Smith leads in English Canada, while Tremblay, meaning a place of aspen trees, is the top name in Quebec, where most Tremblays descend from one 17th-century settler. In Quebec, women keep their own surname after marriage by law. Liam and Olivia top recent baby lists.","tone":1},
"cd":{"boy":{"first":"Glody","last":"Ilunga","say":"GLOH-dee ee-LOON-gah"},
"girl":{"first":"Merveille","last":"Kasongo","say":"mer-VAY kah-SONG-go"},
"about":"Congolese love meaningful French first names like Merveille ('marvel') and Exaucé ('prayer answered'). Ilunga and Kasongo are common Luba names. Under Mobutu's 1970s 'authenticity' policy, Christian names were banned and many people still use an African 'postnom' after their surname.","tone":5},
"cf":{"boy":{"first":"Jean","last":"Dacko","say":"ZHAHN DAK-oh"},
"girl":{"first":"Marie","last":"Samba","say":"mah-REE SAHM-bah"},
"about":"Central Africans usually combine a French, Christian first name with a family name from one of the country's many ethnic groups. Sango is the shared national language, and names in it or in local languages are often given alongside the French one.","tone":5},
"cg":{"boy":{"first":"Exaucé","last":"Malonga","say":"eg-zoh-SAY mah-LONG-gah"},
"girl":{"first":"Grâce","last":"Massamba","say":"GRAHSS mah-SAHM-bah"},
"about":"In Congo-Brazzaville, faith-inspired French names like Exaucé ('prayer answered') and Grâce are popular. Surnames such as Malonga and Massamba come from Kongo-language communities. Children do not always share the father's surname; names may honour a relative instead.","tone":5},
"ch":{"boy":{"first":"Noah","last":"Müller","say":"NO-ah MEW-ler"},
"girl":{"first":"Mia","last":"Meier","say":"MEE-ah MY-er"},
"about":"Müller (miller) and Meier (a farm steward or manager) are Switzerland's top surnames. Every Swiss citizen also has a 'place of origin', the village their family name is historically tied to, which appears on their passport even if they have never lived there.","tone":1},
"ci":{"boy":{"first":"Ibrahim","last":"Koné","say":"ib-rah-HEEM ko-NAY"},
"girl":{"first":"Aya","last":"Kouassi","say":"EYE-ah KWAH-see"},
"about":"Koné and Coulibaly are huge Mandé surnames from the north. In the south, Akan peoples like the Baoulé use day names: Kouassi is a boy born on Sunday, and it has become a common family name. Ivorians often write the family name first in formal contexts.","tone":5},
"cl":{"boy":{"first":"Agustín","last":"González","say":"ah-goos-TEEN gon-SAH-les"},
"girl":{"first":"Sofía","last":"Muñoz","say":"so-FEE-ah moon-YOS"},
"about":"Chileans carry two surnames, father's first and mother's second. González ('son of Gonzalo') and Muñoz are the most common, both from Spain. Agustín and Sofía have been top choices for babies in recent years. Mapuche surnames are also common in the south.","tone":2},
"cm":{"boy":{"first":"Samuel","last":"Mbarga","say":"SAM-yoo-el um-BAR-gah"},
"girl":{"first":"Grace","last":"Ngono","say":"GRAYSS ung-GOH-noh"},
"about":"Cameroon has 250-plus ethnic groups and both French and English as official languages, so names vary a lot. Mbarga and Ngono are typical Beti names from the centre. Many people put the family name first on documents, and a Christian name is often added.","tone":5},
"cn":{"boy":{"first":"Haoran","last":"Wang","say":"HOW-rahn WAHNG"},
"girl":{"first":"Xinyi","last":"Li","say":"SHIN-yee LEE"},
"about":"In China the family name comes first, so locals write Wang Haoran. Wang ('king') and Li ('plum') are the two most common surnames on Earth. Given names are usually one or two characters chosen for meaning; Haoran evokes something vast and upright. Women keep their surname after marriage.","tone":2},
"co":{"boy":{"first":"Santiago","last":"Rodríguez","say":"san-tee-AH-go rod-REE-ges"},
"girl":{"first":"Valentina","last":"Gómez","say":"vah-len-TEE-nah GO-mes"},
"about":"Colombians use two surnames, father's then mother's, so a full name can run to four parts. Rodríguez ('son of Rodrigo') and Gómez are Spanish patronymics. Santiago honours Saint James, and Valentina has long been a favourite girl's name.","tone":3},
"cr":{"boy":{"first":"Sebastián","last":"Jiménez","say":"seh-bas-tee-AHN hee-MEH-nes"},
"girl":{"first":"Valeria","last":"Mora","say":"vah-LEH-ree-ah MOR-ah"},
"about":"Costa Ricans, or Ticos, use two surnames, father's then mother's. Jiménez ('son of Jimeno') and Mora are among the most common. Valeria and Sebastián have been popular baby names in recent decades.","tone":2},
"cu":{"boy":{"first":"Yoandri","last":"Rodríguez","say":"yo-AHN-dree rod-REE-ges"},
"girl":{"first":"Yanelis","last":"González","say":"yah-NEH-lees gon-SAH-les"},
"about":"Cuba is famous for creative first names starting with Y, like Yoandri and Yanelis, a fashion that peaked from the 1970s to 1990s. Cubans carry two Spanish surnames, father's then mother's, with Rodríguez and González the most common.","tone":3},
"cv":{"boy":{"first":"João","last":"Tavares","say":"zhoo-OW tah-VAR-esh"},
"girl":{"first":"Ana","last":"Lopes","say":"AH-nuh LOH-pesh"},
"about":"Cape Verdeans have Portuguese names and often several surnames, mother's and father's. Tavares, Lopes, Silva and Monteiro are very common. Day to day, almost everyone also has a Kriolu nickname, and people may be better known by it than by their official name.","tone":3},
"cy":{"boy":{"first":"Andreas","last":"Georgiou","say":"an-DREH-as yor-YEE-oo"},
"girl":{"first":"Maria","last":"Charalambous","say":"mah-REE-ah ha-ra-LAM-boos"},
"about":"Many Greek Cypriot surnames end in -ou, meaning 'of': Georgiou is '(child) of George', Charalambous '(child) of Charalambos'. Women do not change the ending. Children are traditionally named after their grandparents, so names like Andreas and Maria recur in families.","tone":2},
"cz":{"boy":{"first":"Jakub","last":"Novák","say":"YAH-koob NO-vahk"},
"girl":{"first":"Eliška","last":"Nováková","say":"EH-leesh-kah NO-vah-ko-vah"},
"about":"Novák, the top Czech surname, meant a newcomer to a village. Women's surnames take the ending -ová, so Novák's daughter is Nováková, though since 2022 women may choose the plain form. Czechs also celebrate a 'name day' on the calendar date linked to their first name.","tone":1},
"de":{"boy":{"first":"Ben","last":"Müller","say":"BEN MEW-ler"},
"girl":{"first":"Emma","last":"Schmidt","say":"EM-ah SHMIT"},
"about":"Germany's most common surnames are trades: Müller is a miller and Schmidt a smith. Short, international first names like Ben and Emma have topped German baby lists in recent years. Registry offices check that a chosen first name is suitable for a child.","tone":1},
"dj":{"boy":{"first":"Abdi","last":"Ahmed","say":"AB-dee AH-med"},
"girl":{"first":"Hodan","last":"Ali","say":"HOH-dan AH-lee"},
"about":"Djibouti's Somali and Afar people traditionally have no family surname: a person's own name is followed by their father's and grandfather's names, so the 'surname' here is the father's first name. Many Somalis can recite their paternal line back many generations.","tone":4},
"dk":{"boy":{"first":"William","last":"Nielsen","say":"VIL-yam NEEL-sen"},
"girl":{"first":"Ida","last":"Jensen","say":"EE-dah YEN-sen"},
"about":"Denmark's top surnames end in -sen, 'son of': Nielsen ('son of Niels') and Jensen ('son of Jens'). These were once true patronymics that changed every generation until surnames were fixed by law in the 1800s. Danish first names must come from an approved list or be approved.","tone":1},
"dm":{"boy":{"first":"Jaden","last":"John","say":"JAY-den JON"},
"girl":{"first":"Kiara","last":"Charles","say":"kee-AR-ah CHARLZ"},
"about":"Dominicans (of Dominica) often have surnames that look like first names, such as John, Joseph and Charles, a pattern common across the Eastern Caribbean. French Creole influence shows in names like Charles and Pierre. Dominica is also home to the Indigenous Kalinago people.","tone":4},
"do":{"boy":{"first":"Juan","last":"Pérez","say":"HWAHN PEH-res"},
"girl":{"first":"Daniela","last":"Rodríguez","say":"dah-nee-EH-lah rod-REE-ges"},
"about":"Dominicans use two Spanish surnames, father's then mother's. Pérez ('son of Pedro') and Rodríguez are among the most common. The country is also known for inventive first names, from blends of parents' names to names inspired by English words or celebrities.","tone":3},
"dz":{"boy":{"first":"Yacine","last":"Benali","say":"yah-SEEN ben-AH-lee"},
"girl":{"first":"Amina","last":"Saidi","say":"ah-MEE-nah sah-EE-dee"},
"about":"Many Algerian surnames start with Ben ('son of'), so Benali is 'son of Ali'. Fixed family names were imposed by French colonial civil registries from the 1880s. Yacine comes from Ya-Sin, a chapter of the Quran, and Amina means 'trustworthy'. Berber (Amazigh) names are popular too.","tone":2},
"ec":{"boy":{"first":"Mateo","last":"Zambrano","say":"mah-TEH-oh sam-BRAH-no"},
"girl":{"first":"Camila","last":"Sánchez","say":"kah-MEE-lah SAHN-ches"},
"about":"Ecuadorians carry two surnames, father's then mother's. Zambrano and Sánchez ('son of Sancho') are among the most common. Indigenous Kichwa surnames are frequent in the highlands. Mateo and Camila have been favourite baby names in recent years.","tone":3},
"ee":{"boy":{"first":"Rasmus","last":"Tamm","say":"RAS-moos TAHM"},
"girl":{"first":"Sofia","last":"Mägi","say":"SO-fee-ah MAH-ghee"},
"about":"Most Estonians got surnames only in the 1800s, after serfdom ended, and many picked nature words: Tamm means 'oak', Mägi 'hill', Saar 'island'. Tamm is the most common. Estonian surnames have no male and female forms, so siblings share exactly the same one.","tone":1},
"eg":{"boy":{"first":"Youssef","last":"Mohamed","say":"YOO-sef moh-HAM-ed"},
"girl":{"first":"Mariam","last":"Ahmed","say":"MAR-yam AH-med"},
"about":"Egyptians usually have no inherited family surname in daily use: a full name lists your name, your father's, then your grandfather's. So the 'last name' here is a father's first name. Youssef (Joseph) and Mariam (Mary) are loved by both Muslim and Christian families.","tone":3},
"er":{"boy":{"first":"Yonas","last":"Tesfay","say":"YOH-nas TES-fay"},
"girl":{"first":"Senait","last":"Haile","say":"seh-NAH-eet HAI-leh"},
"about":"Eritreans traditionally use their own name followed by their father's first name, with no shared family surname, so siblings share the second name but parents do not. Tesfay means 'my hope' in Tigrinya, and Haile means 'power' or 'strength'.","tone":4},
"es":{"boy":{"first":"Hugo","last":"García","say":"OO-go gar-THEE-ah"},
"girl":{"first":"Lucía","last":"Martínez","say":"loo-THEE-ah mar-TEE-neth"},
"about":"Every Spaniard has two surnames, traditionally father's first and mother's second (parents can now choose the order). García is the most common; Martínez means 'son of Martín'. Women keep their own surnames after marriage. Hugo and Lucía topped recent baby charts.","tone":2},
"et":{"boy":{"first":"Dawit","last":"Bekele","say":"DAH-wit beh-KEH-leh"},
"girl":{"first":"Hana","last":"Tesfaye","say":"HAH-nah tes-FAH-yeh"},
"about":"Ethiopians have no family surname: the second name is simply the father's first name, and a grandfather's may follow. So Dawit Bekele's son might be Abel Dawit. People are addressed by first name, even formally. Dawit is the Ge'ez form of David, and Tesfaye means 'my hope'.","tone":4},
"fi":{"boy":{"first":"Onni","last":"Korhonen","say":"ON-nee KOR-ho-nen"},
"girl":{"first":"Aino","last":"Virtanen","say":"EYE-no VEER-tah-nen"},
"about":"Many Finnish surnames end in -nen, a small 'of' ending. Korhonen is the most common, and Virtanen comes from virta, 'stream'. Onni means 'luck' or 'happiness', and Aino is a heroine of the national epic, the Kalevala. Finns also celebrate name days.","tone":1},
"fj":{"boy":{"first":"Josaia","last":"Waqa","say":"joh-SAI-ah WANG-gah"},
"girl":{"first":"Litia","last":"Naivalu","say":"lee-TEE-ah nai-VAH-loo"},
"about":"Indigenous Fijians often use Fijianised Bible names like Josaia (Josiah) and Litia (Lydia). In Fijian spelling q sounds like 'ngg', so Waqa is 'WANG-gah'. Fiji also has a large Indo-Fijian community, whose names come from Hindi, Muslim and Christian traditions.","tone":4},
"fm":{"boy":{"first":"Jonathan","last":"Simina","say":"JON-ah-thun see-MEE-nah"},
"girl":{"first":"Maria","last":"Panuelo","say":"mah-REE-ah pan-WEH-lo"},
"about":"Micronesians usually have Christian first names from missionary times. Family surnames were adopted fairly recently, often from a father's or grandfather's name, under Spanish, German, Japanese and US rule. Belonging to your mother's clan still matters greatly in many islands.","tone":4},
"fr":{"boy":{"first":"Gabriel","last":"Martin","say":"gah-bree-EL mar-TAN"},
"girl":{"first":"Louise","last":"Bernard","say":"loo-EEZ ber-NAR"},
"about":"Martin, France's most common surname, comes from the popular Saint Martin of Tours and originally from Mars, the Roman god. Bernard is Germanic for 'brave as a bear'. Gabriel and Louise have topped French baby charts recently. Children may take either or both parents' surnames.","tone":1},
"ga":{"boy":{"first":"Jean","last":"Nguema","say":"ZHAHN ung-GWEH-mah"},
"girl":{"first":"Grâce","last":"Ondo","say":"GRAHSS ON-doh"},
"about":"Gabonese usually combine a French, often Christian first name with a family name from local languages. Nguema, Ondo and Obiang are typical Fang names; the Fang are Gabon's largest group. Officially the family name is often written first.","tone":5},
"gb":{"boy":{"first":"Oliver","last":"Smith","say":"OL-iv-er SMITH"},
"girl":{"first":"Olivia","last":"Jones","say":"oh-LIV-ee-uh JOHNZ"},
"about":"Smith, a metalworker, is Britain's most common surname, while Jones ('son of John') is especially Welsh. Many English surnames come from jobs, places or nicknames. Oliver and Olivia have both spent years at the top of the baby-name lists.","tone":1},
"gd":{"boy":{"first":"Kareem","last":"Mitchell","say":"kah-REEM MITCH-ul"},
"girl":{"first":"Shania","last":"James","say":"shah-NYE-ah JAYMZ"},
"about":"Grenadian surnames are mostly British or French from colonial times, and surnames that look like first names, such as James, Charles and Joseph, are very common. Mitchell is of Scottish and English origin. First names follow lively Caribbean and American trends.","tone":4},
"ge":{"boy":{"first":"Giorgi","last":"Beridze","say":"GYOR-gee beh-REED-zeh"},
"girl":{"first":"Nino","last":"Maisuradze","say":"NEE-no mai-soo-RAD-zeh"},
"about":"Georgian surnames reveal a lot: -dze ('son of') is common in the west and -shvili ('child of') in the east. Beridze is the most common surname. Giorgi honours Saint George, the country's patron saint, and Nino the woman who brought Christianity to Georgia.","tone":1},
"gh":{"boy":{"first":"Kwame","last":"Mensah","say":"KWAH-meh MEN-sah"},
"girl":{"first":"Ama","last":"Owusu","say":"AH-mah oh-WOO-soo"},
"about":"Akan Ghanaians get a day name for the weekday they were born: Kwame is a Saturday boy and Ama a Saturday girl. Mensah is traditionally a name for a third son, and like Owusu it now works as a surname. Many Ghanaians also have an English or Christian first name.","tone":5},
"gm":{"boy":{"first":"Lamin","last":"Ceesay","say":"LAH-min SEE-say"},
"girl":{"first":"Fatou","last":"Jallow","say":"FAH-too JAH-low"},
"about":"Gambian names blend Islam with local tradition: Lamin comes from al-Amin, 'the trustworthy', and Fatou is a local form of Fatima. Ceesay is a Mandinka name and Jallow a Fula one, so surnames often hint at ethnic group. Babies are named at a ceremony a week after birth.","tone":5},
"gn":{"boy":{"first":"Mamadou","last":"Diallo","say":"MAH-mah-doo jah-LOH"},
"girl":{"first":"Mariama","last":"Barry","say":"mah-ree-AH-mah BAH-ree"},
"about":"Diallo and Barry are classic Fula (Peul) surnames, the largest group in Guinea, while Camara and Condé are Malinké names. Mamadou is a West African form of Muhammad and Mariama of Maryam (Mary). Surnames usually signal a person's ethnic group.","tone":5},
"gq":{"boy":{"first":"José","last":"Obiang","say":"ho-SEH oh-bee-ANG"},
"girl":{"first":"María","last":"Nchama","say":"mah-REE-ah un-CHAH-mah"},
"about":"Equatorial Guinea is Africa's only Spanish-speaking country, so Spanish first names are paired with family names from the Fang and Bubi peoples. Obiang and Nchama are typical Fang names, as are Nguema and Ondo. Spanish custom of two surnames is often followed.","tone":5},
"gr":{"boy":{"first":"Giorgos","last":"Papadopoulos","say":"YOR-gos pa-pa-DO-poo-los"},
"girl":{"first":"Maria","last":"Papadopoulou","say":"ma-REE-a pa-pa-do-POO-loo"},
"about":"Giorgos is the Greek form of George, meaning farmer. Papadopoulos means son of the priest: papas plus -poulos, a Peloponnese ending for descendant. Women use the genitive form, so a sister is Papadopoulou. Children are traditionally named after their grandparents.","tone":2},
"gt":{"boy":{"first":"José","last":"López","say":"ho-SAY LO-pes"},
"girl":{"first":"María","last":"García","say":"ma-REE-a gar-SEE-a"},
"about":"Guatemalans carry two surnames, the father's first and then the mother's. López means son of Lope, and García is an old Iberian name. Many Maya families also use surnames such as Xol or Tzoc, and Spanish saints' names like José and María are hugely popular.","tone":3},
"gw":{"boy":{"first":"Mamadu","last":"Baldé","say":"ma-MA-doo bal-DAY"},
"girl":{"first":"Fatumata","last":"Djaló","say":"fa-too-MA-ta ja-LO"},
"about":"Mamadu and Fatumata are local forms of Muhammad and Fatima, popular among Muslim Fula families. Baldé and Djaló are Fula clan names. Christian families more often use Portuguese names like João and Maria with surnames such as Gomes or Mendes, a legacy of the colonial era.","tone":5},
"gy":{"boy":{"first":"Ravi","last":"Singh","say":"RAH-vee SING"},
"girl":{"first":"Priya","last":"Persaud","say":"PREE-ya per-SAWD"},
"about":"Guyana mixes Indian, African, Indigenous and other roots. Singh means lion, and Persaud is the local spelling of Prasad, a blessed offering, carried by indentured workers from India. Afro-Guyanese families often have British surnames like Williams or Thomas.","tone":3},
"hn":{"boy":{"first":"José","last":"Hernández","say":"ho-SAY er-NAN-des"},
"girl":{"first":"Daniela","last":"López","say":"da-NYEH-la LO-pes"},
"about":"Hondurans use two surnames, the father's then the mother's. Hernández means son of Hernando, and López son of Lope. Saints' names like José are perennial favourites, while names like Daniela reflect newer trends. Garifuna communities on the coast have their own naming traditions.","tone":3},
"hr":{"boy":{"first":"Luka","last":"Horvat","say":"LOO-ka HOR-vat"},
"girl":{"first":"Mia","last":"Kovačević","say":"MEE-a ko-VA-cheh-vich"},
"about":"Luka, the Croatian form of Luke, has topped the charts for years. Horvat, the most common surname, is simply an old word for a Croat. Kovačević means son of the smith: the ending -ić means little one or descendant and is found in countless Croatian surnames.","tone":1},
"ht":{"boy":{"first":"Jean","last":"Pierre","say":"ZHAHN pee-AIR"},
"girl":{"first":"Marie","last":"Joseph","say":"ma-REE zho-ZEF"},
"about":"Many Haitian surnames, like Pierre, Joseph and Jean-Baptiste, are French first names. Given names are often compounds such as Jean-Marc or Marie-Carmelle, reflecting French Catholic heritage. In daily life people may go by a Creole nickname as well.","tone":5},
"hu":{"boy":{"first":"Bence","last":"Nagy","say":"BEN-tseh NODJ"},
"girl":{"first":"Hanna","last":"Kovács","say":"HON-na KO-vaach"},
"about":"Hungarians write the family name first, so he is Nagy Bence at home. Nagy means big and Kovács means smith, the two most common surnames. Bence comes from the Latin Vincent. Every Hungarian name also has a name day, celebrated much like a small birthday.","tone":1},
"id":{"boy":{"first":"Budi","last":"Santoso","say":"BOO-dee san-TOH-so"},
"girl":{"first":"Dewi","last":"Lestari","say":"DAY-wee les-TAH-ree"},
"about":"Many Indonesians, especially Javanese, have no family name at all, and some have just one name. Budi comes from Sanskrit buddhi, wisdom, and Dewi means goddess. Santoso and Lestari are Javanese words, roughly calm and contented, and everlasting.","tone":3},
"ie":{"boy":{"first":"Jack","last":"Murphy","say":"JAK MUR-fee"},
"girl":{"first":"Grace","last":"Kelly","say":"GRAYSS KEL-ee"},
"about":"Murphy comes from Irish Ó Murchadha, descendant of Murchadh, a name linked to the sea. Kelly is from Ó Ceallaigh. Ó means grandson or descendant and Mac means son of, prefixes many families dropped and later restored. Irish-language names like Seán and Saoirse are popular too.","tone":1},
"il":{"boy":{"first":"Noam","last":"Cohen","say":"no-AHM ko-HEN"},
"girl":{"first":"Noa","last":"Levi","say":"NO-ah leh-VEE"},
"about":"Noam means pleasantness, and Noa is a biblical daughter of Zelophehad. Cohen marks descent from the priestly line of Aaron, and Levi from the tribe of Levi. Many immigrants swapped European surnames for Hebrew ones, and Arab citizens follow Arabic naming customs.","tone":2},
"in":{"boy":{"first":"Aarav","last":"Sharma","say":"AA-rav SHAR-ma"},
"girl":{"first":"Ananya","last":"Patel","say":"a-NUN-ya pa-TEL"},
"about":"Indian surnames often reveal region or community: Sharma is a traditional Brahmin name in the north, while Patel, from a word for village headman, is typically Gujarati. Many South Indians use a father's or village name instead. Ananya means unique and Aarav is a modern favourite.","tone":4},
"iq":{"boy":{"first":"Ali","last":"Hussein","say":"AH-lee hoo-SAYN"},
"girl":{"first":"Zainab","last":"Hassan","say":"ZAY-nab HA-san"},
"about":"Iraqis traditionally string together their own name, their father's and their grandfather's, so the last name is often a grandfather's given name, sometimes followed by a tribal name. Ali, Hussein, Hassan and Zainab honour revered members of the Prophet's family.","tone":3},
"ir":{"boy":{"first":"Amir","last":"Hosseini","say":"a-MEER ho-say-NEE"},
"girl":{"first":"Zahra","last":"Mohammadi","say":"zah-RAH mo-ham-ma-DEE"},
"about":"Iranians only adopted official surnames in the 1920s, and many end in -i, meaning of or from. Hosseini often marks claimed descent from Imam Hussein. Amir means prince or commander, and Zahra, radiant, honours Fatima Zahra, the Prophet's daughter.","tone":2},
"is":{"boy":{"first":"Jón","last":"Jónsson","say":"YOHN YOHNS-son"},
"girl":{"first":"Anna","last":"Jónsdóttir","say":"AN-na YOHNS-doh-teer"},
"about":"Iceland keeps the old Norse patronymic system: a child's last name is the father's (or sometimes mother's) first name plus -son or -dóttir. So Jón's son is Jónsson and his daughter Jónsdóttir. Phone books list people by first name, and new names need approval from a naming committee.","tone":1},
"it":{"boy":{"first":"Francesco","last":"Rossi","say":"fran-CHES-ko ROS-see"},
"girl":{"first":"Sofia","last":"Russo","say":"so-FEE-a ROOS-so"},
"about":"Rossi and Russo both started as nicknames for someone red-haired: Rossi is the northern form and Russo the southern. Francesco honours Saint Francis of Assisi, Italy's patron saint, and Sofia means wisdom in Greek. Italian women legally keep their own surname after marriage.","tone":2},
"jm":{"boy":{"first":"Andre","last":"Brown","say":"AHN-dray BROWN"},
"girl":{"first":"Shanice","last":"Williams","say":"sha-NEESS WIL-yamz"},
"about":"Most Jamaican surnames, like Brown, Williams and Campbell, are British, a legacy of the colonial and slavery era, with many Scottish names in the mix. Given names are often inventive and modern, and nearly everyone also has a nickname or pet name used by family and friends.","tone":5},
"jo":{"boy":{"first":"Omar","last":"Al-Zoubi","say":"OH-mar az-ZOO-bee"},
"girl":{"first":"Sara","last":"Al-Masri","say":"SA-ra al-MAS-ree"},
"about":"Many Jordanian family names point to a tribe or origin: Al-Masri means the Egyptian, and Al-Zoubi is a large tribal family from the north. Formally, people may be named as son of (bin) or daughter of (bint) their father. Omar recalls the second caliph, and Sara is the biblical Sarah.","tone":2},
"jp":{"boy":{"first":"Haruto","last":"Sato","say":"ha-ROO-toh SAH-toh"},
"girl":{"first":"Yui","last":"Suzuki","say":"YOO-ee soo-ZOO-kee"},
"about":"Japanese write the family name first, so he is Sato Haruto. Sato and Suzuki are the two most common surnames; Suzuki is usually written with the characters for bell and tree. Given names are built from kanji chosen for meaning: haru can mean sun or spring, and Yui can mean tie or bond.","tone":2},
"ke":{"boy":{"first":"Brian","last":"Otieno","say":"BRY-an oh-tee-EH-no"},
"girl":{"first":"Mercy","last":"Wanjiku","say":"MUR-see wan-JEE-koo"},
"about":"Kenyans often pair an English or Christian name with an ethnic one. Otieno is a Luo name for a boy born at night. Wanjiku comes from one of the nine Kikuyu clans and is often given after a grandmother. Many people use a father's name or their own ethnic name as a surname.","tone":5},
"kg":{"boy":{"first":"Aibek","last":"Asanov","say":"ai-BEK a-SA-nov"},
"girl":{"first":"Aijan","last":"Asanova","say":"ai-JAN a-SA-no-va"},
"about":"Ai means moon in Kyrgyz and shows up in many names: bek means lord and jan means soul. Surnames are often a grandfather's or father's name with Russian-style -ov or -ova; Asan is a form of Hassan. Some families now prefer uulu (son of) or kyzy (daughter of) instead.","tone":2},
"kh":{"boy":{"first":"Dara","last":"Sok","say":"DAH-ra SOK"},
"girl":{"first":"Sophea","last":"Chan","say":"so-PEE-a CHAN"},
"about":"Cambodians write the family name first, so he is Sok Dara. Many family names are simply a father's or grandfather's given name, so siblings and parents can differ. Sok comes from a word for happiness and well-being, and Dara means star.","tone":4},
"ki":{"boy":{"first":"Ioane","last":"Tebano","say":"yo-AH-neh teh-BAH-no"},
"girl":{"first":"Maria","last":"Tebano","say":"ma-REE-a teh-BAH-no"},
"about":"Many I-Kiribati first names are local forms of biblical names brought by missionaries, like Ioane for John. Surnames are often a father's given name, and many traditional names begin with Te, the Gilbertese word for the. In Gilbertese spelling ti sounds like s, as in Kiribati.","tone":4},
"km":{"boy":{"first":"Ahamada","last":"Soilihi","say":"a-ha-MA-da soy-LEE-hee"},
"girl":{"first":"Mariama","last":"Ali","say":"ma-ree-AH-ma AH-lee"},
"about":"Comorian names are mostly Arabic and Islamic, reshaped by the local language: Ahamada is Ahmad and Soilihi is Salih. Traditionally there is no fixed family name, so a child's second name is usually the father's given name. Mariama is a local form of Maryam.","tone":4},
"kn":{"boy":{"first":"Jaden","last":"Liburd","say":"JAY-den LIE-burd"},
"girl":{"first":"Keisha","last":"Browne","say":"KEE-sha BROWN"},
"about":"Kittitian and Nevisian surnames are largely British, dating from the colonial plantation era, and spellings like Browne with an e are common across the Eastern Caribbean. Liburd is a name strongly associated with the islands. Given names tend to be modern and inventive.","tone":5},
"kp":{"boy":{"first":"Kwang-chol","last":"Kim","say":"KWANG-chol KIM"},
"girl":{"first":"Song-hui","last":"Ri","say":"SUNG-hee REE"},
"about":"North Koreans write the family name first, so he is Kim Kwang-chol. Ri is the northern spelling of Lee or Yi, as the North keeps the initial R. Given names usually have two syllables, each with its own meaning; chol means iron and is a popular element for boys.","tone":2},
"kr":{"boy":{"first":"Min-jun","last":"Kim","say":"MIN-joon KIM"},
"girl":{"first":"Seo-yeon","last":"Lee","say":"SUH-yun LEE"},
"about":"Koreans write the family name first: Kim Min-jun. Kim, Lee and Park cover nearly half the population, but each is split into clans by ancestral home, like the Gimhae Kims. Women keep their own surname after marriage. Given names are two syllables chosen from Chinese-derived meanings.","tone":2},
"kw":{"boy":{"first":"Mohammad","last":"Al-Mutairi","say":"mo-HAM-mad al-mu-TAY-ree"},
"girl":{"first":"Noura","last":"Al-Enezi","say":"NOO-ra al-a-NEH-zee"},
"about":"Many Kuwaiti family names name a tribe: Al-Mutairi comes from the Mutair and Al-Enezi from the Anazah, both large Arabian tribes. Formally, a person's name strings together their father's and grandfather's names. Noura comes from the Arabic word for light.","tone":3},
"kz":{"boy":{"first":"Alikhan","last":"Akhmetov","say":"a-lee-KHAN akh-MEH-tov"},
"girl":{"first":"Aruzhan","last":"Omarova","say":"a-roo-ZHAN o-MA-ro-va"},
"about":"Aruzhan blends Kazakh aru, beautiful, with zhan, soul. Alikhan joins Ali with khan, ruler. Surnames are usually an ancestor's name with Russian-style -ov or -ova, here from Akhmet (Ahmad) and Omar, though some families now use -uly (son of) or -kyzy (daughter of).","tone":2},
"la":{"boy":{"first":"Khamla","last":"Vongsa","say":"KHAM-la WONG-sa"},
"girl":{"first":"Manivone","last":"Phommachanh","say":"ma-nee-WON pom-ma-CHAN"},
"about":"In Laos people are addressed by their first name with a polite title, and family names came into general use only in the twentieth century. Kham, meaning gold, is a popular element in names. Lao v is said like w, and almost everyone also has a short nickname.","tone":3},
"lb":{"boy":{"first":"Elie","last":"Khoury","say":"EH-lee KHOO-ree"},
"girl":{"first":"Maya","last":"Haddad","say":"MY-ya had-DAD"},
"about":"Lebanese names often hint at religion and history. Khoury means priest, a common Christian surname, and Haddad means smith. Elie is the French-style form of Elijah, while Muslim families favour names like Mohammad or Fatima. French and Arabic influences mix freely.","tone":2},
"lc":{"boy":{"first":"Jaden","last":"Joseph","say":"JAY-den JO-sef"},
"girl":{"first":"Kimberly","last":"Charles","say":"KIM-ber-lee CHARLZ"},
"about":"Saint Lucia changed hands between France and Britain many times, and it shows in surnames like Joseph, Charles and Jn Baptiste, which are French first names. English is official, but many people also speak Kwéyòl, a French-based Creole, and modern English given names are popular.","tone":5},
"li":{"boy":{"first":"Luca","last":"Frick","say":"LOO-ka FRIK"},
"girl":{"first":"Lena","last":"Büchel","say":"LAY-na BUE-khel"},
"about":"Liechtenstein's old families, such as Büchel, Frick, Marxer and Beck, have lived in its villages for centuries. Büchel is thought to come from a dialect word for a small hill. Naming follows German-speaking custom, with short international names like Luca and Lena in fashion.","tone":1},
"lk":{"boy":{"first":"Kasun","last":"Perera","say":"KA-sun peh-REH-ra"},
"girl":{"first":"Nethmi","last":"Fernando","say":"NETH-mee fer-NAN-do"},
"about":"Perera and Fernando, among Sri Lanka's most common surnames, date from Portuguese rule in the 1500s, when many coastal Sinhalese took Portuguese names. Older Sinhalese names include a ge name, the ancestral house. Tamil families usually use the father's given name instead of a surname.","tone":4},
"lr":{"boy":{"first":"Emmanuel","last":"Johnson","say":"ee-MAN-yoo-el JON-sun"},
"girl":{"first":"Comfort","last":"Kollie","say":"KUM-fert KOL-ee"},
"about":"Liberia was founded by freed African Americans, so English surnames like Johnson are widespread. Indigenous peoples such as the Kpelle and Bassa have their own names, including Kollie. Virtue names like Comfort, Patience and Blessing and biblical names like Emmanuel are popular.","tone":5},
"ls":{"boy":{"first":"Thabo","last":"Mokoena","say":"TAH-bo mo-KWEH-na"},
"girl":{"first":"Palesa","last":"Molapo","say":"pa-LEH-sa mo-LA-po"},
"about":"Sesotho names carry clear meanings: Thabo means joy and Palesa means flower. Mokoena is linked to the Bakoena, the people of the crocodile, the totem of Lesotho's royal line. Molapo is a prominent family descended from King Moshoeshoe. Most people also have an English name.","tone":5},
"lt":{"boy":{"first":"Lukas","last":"Kazlauskas","say":"LOO-kas kaz-LOWS-kas"},
"girl":{"first":"Emilija","last":"Kazlauskaitė","say":"eh-MEE-lee-ya kaz-lows-KAI-tay"},
"about":"Lithuanian surnames change with gender and marital status: an unmarried daughter adds -aitė or -ytė, and a married woman traditionally -ienė, though a neutral -ė form is also allowed. Kazlauskas is a Lithuanian form of the Polish Kozłowski, from koza, goat.","tone":1},
"lu":{"boy":{"first":"Luca","last":"Schmit","say":"LOO-ka SHMIT"},
"girl":{"first":"Emma","last":"Muller","say":"EM-ma MUL-ler"},
"about":"Schmit means smith and Muller means miller, both common in Luxembourgish spelling. The country is trilingual, so names drift between French, German and Luxembourgish forms, and Portuguese names like Da Silva are common thanks to a large community. Luca and Emma are favourites.","tone":1},
"lv":{"boy":{"first":"Roberts","last":"Bērziņš","say":"ROO-berts BAIR-zinsh"},
"girl":{"first":"Sofija","last":"Bērziņa","say":"SO-fee-ya BAIR-zi-na"},
"about":"Latvian names take grammatical endings, so even Robert becomes Roberts, and surnames change for women: Bērziņš becomes Bērziņa. Bērziņš means little birch, and many surnames come from nature. Latvians celebrate name days, and stress almost always falls on the first syllable.","tone":1},
"ly":{"boy":{"first":"Ahmed","last":"Al-Warfalli","say":"AH-med al-war-FAL-lee"},
"girl":{"first":"Fatima","last":"Al-Obeidi","say":"FA-ti-ma al-o-BAY-dee"},
"about":"Many Libyan family names come from tribes: Al-Warfalli from the Warfalla, one of the largest, and Al-Obeidi from the Obeidat of the east. Formally a person's name also includes their father's and grandfather's names. Fatima honours the Prophet's daughter.","tone":3},
"ma":{"boy":{"first":"Mohamed","last":"Alaoui","say":"mo-HA-med a-la-WEE"},
"girl":{"first":"Fatima Zahra","last":"Bennani","say":"FA-ti-ma ZAH-ra ben-NA-nee"},
"about":"Alaoui signals claimed descent from the Prophet through the same line as Morocco's royal family. Bennani is an old Fez family name. Compound names like Fatima Zahra are very popular, and Amazigh names such as Yuba or Tilelli have gained ground since restrictions on them eased.","tone":3},
"mc":{"boy":{"first":"Louis","last":"Gastaud","say":"LOO-ee gas-TOH"},
"girl":{"first":"Charlotte","last":"Pastor","say":"shar-LOT pas-TOR"},
"about":"Only a minority of Monaco's residents are Monégasque citizens, from old families like Gastaud and Pastor. Names follow French and Italian custom, and royal names such as Louis and Charlotte, both used by the Grimaldi family, are classic choices.","tone":1},
"md":{"boy":{"first":"Alexandru","last":"Rusu","say":"a-lek-SAN-droo ROO-soo"},
"girl":{"first":"Maria","last":"Ceban","say":"ma-REE-a cheh-BAN"},
"about":"Moldovan names follow Romanian custom. Rusu originally meant the Russian, and Ceban comes from a word for shepherd, borrowed from Turkish çoban. Orthodox saints' names like Alexandru and Maria are long-standing favourites, and name days are widely celebrated.","tone":1},
"me":{"boy":{"first":"Luka","last":"Popović","say":"LOO-ka PO-po-vich"},
"girl":{"first":"Milica","last":"Vujović","say":"MEE-li-tsa VOO-yo-vich"},
"about":"Popović means son of the priest, from pop. The ending -ić, little one or descendant, appears in most Montenegrin surnames. Families traditionally belong to a bratstvo, a brotherhood of related clans. Milica comes from mil, dear or gracious.","tone":1},
"mg":{"boy":{"first":"Hery","last":"Rakotomalala","say":"HAIR-ee ra-koo-too-MAH-la-la"},
"girl":{"first":"Hanitra","last":"Rasoa","say":"HA-neech ra-SOO"},
"about":"Malagasy names can be wonderfully long and often start with Ra-, a mark of respect. Rakoto is a classic name element, and many surnames were built from an ancestor's name rather than shared family-wide. Hery means strength and Hanitra means fragrance.","tone":4},
"mh":{"boy":{"first":"Jonathan","last":"Kabua","say":"JON-a-than ka-BOO-a"},
"girl":{"first":"Lijon","last":"Langidrik","say":"LEE-jon LANG-id-rik"},
"about":"Marshallese often take a parent's given name as their surname, so families may not share one. Kabua is the name of a prominent chiefly family. Many traditional women's names begin with Li-, while biblical and English names arrived with missionaries.","tone":4},
"mk":{"boy":{"first":"Luka","last":"Stojanovski","say":"LOO-ka sto-ya-NOV-skee"},
"girl":{"first":"Mila","last":"Nikolovska","say":"MEE-la nee-KO-lov-ska"},
"about":"Most Macedonian surnames end in -ski for men and -ska for women, often built on a forefather's name: Stojanovski from Stojan, Nikolovska from Nikola. Ethnic Albanians, a large minority, follow their own naming traditions. Mila comes from mil, dear.","tone":1},
"ml":{"boy":{"first":"Moussa","last":"Traoré","say":"MOO-sa tra-oh-RAY"},
"girl":{"first":"Aminata","last":"Diarra","say":"a-mee-NA-ta JAR-ra"},
"about":"In Mali the surname, or jamu, ties you to an ancient clan, and some clans share joking-cousin bonds that let them tease each other freely. Traoré and Diarra are old Mande clan names. Moussa is Moses and Aminata honours Amina, the Prophet's mother.","tone":5},
"mm":{"boy":{"first":"Aung","last":"Kyaw","say":"AWNG CHAW"},
"girl":{"first":"Thandar","last":"Win","say":"THAN-dar WIN"},
"about":"Most people in Myanmar have no surname at all, so parents and children rarely share a name. Names are often chosen by the day of the week a child is born, which sets the starting letter. Aung means success. Honorifics like Maung for boys and Ma for girls go before the name.","tone":3},
"mn":{"boy":{"first":"Bat-Erdene","last":"Ganbaatar","say":"BAT-er-den GAN-baa-tar"},
"girl":{"first":"Nomin","last":"Bold","say":"NO-min BOLD"},
"about":"Mongolians are known by their given name, preceded by the father's (or sometimes mother's) name. Bat means strong and erdene jewel; Ganbaatar is steel hero, and Bold means steel. Clan names were restored in the 2000s, and so many chose Borjigin, Genghis Khan's clan, that it is the most common.","tone":2},
"mr":{"boy":{"first":"Mohamed","last":"Ould Ahmed","say":"mo-HA-med ood AH-med"},
"girl":{"first":"Mariem","last":"Mint Mohamed","say":"MAR-yem mint mo-HA-med"},
"about":"Among Mauritania's Arabic-speaking majority, the last name usually links you to your father: Ould means son of and Mint means daughter of, in the local Hassaniya dialect. So siblings each carry their father's name. Mariem is a local form of Maryam.","tone":4},
"mt":{"boy":{"first":"Luke","last":"Borg","say":"LOOK BORG"},
"girl":{"first":"Maria","last":"Vella","say":"ma-REE-a VEL-la"},
"about":"Maltese surnames mix Semitic, Italian and English roots. Borg, the most common, is thought to come from a word for a tower. Catholic saints' names are traditional, and many people celebrate the feast of their village patron as much as their own birthday.","tone":2},
"mu":{"boy":{"first":"Rohan","last":"Ramsamy","say":"RO-han ram-SA-mee"},
"girl":{"first":"Priya","last":"Ramdin","say":"PREE-ya ram-DEEN"},
"about":"Most Mauritians descend from Indian indentured workers, and many surnames grew from an ancestor's given name noted on arrival: Ramsamy is Tamil and Ramdin north Indian. Creole, Chinese and Franco-Mauritian families add French and Hakka names to the mix.","tone":3},
"mv":{"boy":{"first":"Ahmed","last":"Ibrahim","say":"AH-med ib-ra-HEEM"},
"girl":{"first":"Aishath","last":"Mohamed","say":"AA-ee-shath mo-HA-med"},
"about":"Maldivians traditionally have no family surname; the second name is usually the father's given name. Aishath is the distinctive Maldivian spelling of Aisha. Because so many people share the same few names, nicknames and the name of a person's house or island help tell them apart.","tone":4},
"mw":{"boy":{"first":"Mphatso","last":"Banda","say":"um-PAHT-so BAN-da"},
"girl":{"first":"Chikondi","last":"Phiri","say":"chi-KON-dee PEE-ree"},
"about":"Chichewa names often carry a message: Mphatso means gift and Chikondi means love. Banda and Phiri are among the most common clan names of the Chewa people. Many Malawians also have an English or biblical first name used at school and work.","tone":5},
"mx":{"boy":{"first":"Santiago","last":"Hernández","say":"san-tee-AH-go er-NAN-des"},
"girl":{"first":"Sofía","last":"García","say":"so-FEE-a gar-SEE-a"},
"about":"Mexicans carry two surnames, the father's first and the mother's second, so someone might be Santiago Hernández López. Hernández means son of Hernando. Santiago honours Saint James, and Sofía means wisdom. Many families also mark the feast day of a child's saint.","tone":3},
"my":{"boy":{"first":"Muhammad Adam","last":"bin Abdullah","say":"moo-HAM-mad AH-dam bin ab-DOOL-lah"},
"girl":{"first":"Nur Aisyah","last":"binti Ahmad","say":"NOOR ai-SHAH bin-TEE AH-mad"},
"about":"Malays have no surnames: the name is given name plus bin (son of) or binti (daughter of) and the father's name. Nur means light. Chinese Malaysians write the family name first, like Tan or Lim, and Indian Malaysians often use the father's name as an initial.","tone":3},
"mz":{"boy":{"first":"Carlos","last":"Cossa","say":"KAR-loosh KO-sa"},
"girl":{"first":"Ana","last":"Machava","say":"AH-na ma-SHA-va"},
"about":"Mozambicans usually pair a Portuguese first name, a legacy of colonial rule, with an African surname. Cossa and Machava are common in the south among Changana-speaking families. Many people also have a family or ethnic name used at home alongside the official one.","tone":5},
"na":{"boy":{"first":"Johannes","last":"Shikongo","say":"yo-HAN-nes shee-KON-go"},
"girl":{"first":"Ndapandula","last":"Nangolo","say":"n-da-pan-DOO-la nan-GO-lo"},
"about":"Most Namibians are Oshiwambo speakers, whose names often express feelings at a birth: Ndapandula means thank you. Biblical names like Johannes came with Finnish and German missionaries. Surnames often began as a father's or grandfather's given name.","tone":5},
"ne":{"boy":{"first":"Ibrahim","last":"Issoufou","say":"ib-ra-HEEM ee-soo-FOO"},
"girl":{"first":"Aïchatou","last":"Moussa","say":"ai-sha-TOO MOO-sa"},
"about":"Names in Niger are mostly Islamic, with French spellings: Issoufou is Yusuf, Moussa is Moses and Aïchatou is Aisha with a Hausa or Fula flourish. The surname is often simply the father's given name, so it can change each generation.","tone":5},
"ng":{"boy":{"first":"Chinedu","last":"Okafor","say":"chee-NEH-doo oh-KAH-for"},
"girl":{"first":"Temitope","last":"Adeyemi","say":"teh-mee-TOH-peh ah-deh-YEH-mee"},
"about":"Nigerian names carry meaning. Igbo Chinedu means God leads, and Okafor marks a boy born on Afor market day. Yoruba Temitope means mine is worthy of thanks, and the Ade in Adeyemi means crown, hinting at royal links. Hausa families favour Islamic names.","tone":5},
"ni":{"boy":{"first":"Luis","last":"Gutiérrez","say":"loo-EES goo-tee-EH-res"},
"girl":{"first":"María José","last":"López","say":"ma-REE-a ho-SAY LO-pes"},
"about":"Nicaraguans use two surnames, the father's then the mother's. Gutiérrez means son of Gutierre and López son of Lope. Compound names like María José, which pairs Mary and Joseph, are popular for girls, and people often go by a short nickname in daily life.","tone":3},
"nl":{"boy":{"first":"Daan","last":"de Jong","say":"DAHN deh YONG"},
"girl":{"first":"Emma","last":"Jansen","say":"EM-ma YAHN-sen"},
"about":"Many Dutch only took fixed surnames when Napoleon required them in 1811. De Jong means the young one and Jansen son of Jan. Small words like de and van are written lowercase after a first name and are ignored when sorting alphabetically, so de Jong is filed under J.","tone":1},
"no":{"boy":{"first":"Jakob","last":"Hansen","say":"YAH-kob HAHN-sen"},
"girl":{"first":"Nora","last":"Johansen","say":"NO-ra yo-HAHN-sen"},
"about":"Hansen and Johansen began as patronymics, son of Hans and son of Johan, before becoming fixed family names in the 1800s. Many Norwegians instead took the name of their family farm, like Haugen, the hill. Nora and Jakob have been top choices in recent years.","tone":1},
"np":{"boy":{"first":"Aayush","last":"Thapa","say":"AA-yush TAH-pa"},
"girl":{"first":"Anisha","last":"Shrestha","say":"a-NEE-sha SHRES-ta"},
"about":"Nepali surnames usually reveal community or ethnic group: Shrestha is a Newar name from the Kathmandu Valley, while Thapa is a Chhetri and Magar name tied to a famous military family. Aayush means long life. Kids also often have nicknames like Kanchha for the youngest son.","tone":3},
"nr":{"boy":{"first":"Jayden","last":"Dabwido","say":"JAY-den dab-WEE-do"},
"girl":{"first":"Ruby","last":"Adeang","say":"ROO-bee a-dee-ANG"},
"about":"Nauruans belong to one of twelve traditional clans, passed down through the mother. Surnames like Dabwido and Adeang are Nauruan, while first names are usually English. The island is tiny, so a person's family and clan are well known to nearly everyone.","tone":4},
"nz":{"boy":{"first":"Oliver","last":"Smith","say":"OL-iv-er SMITH"},
"girl":{"first":"Charlotte","last":"Wilson","say":"SHAR-lut WIL-sun"},
"about":"Most New Zealanders carry British-origin names: Smith is an occupational name for a metalworker, Wilson means son of Will. Maori names such as Nikau or Aroha are increasingly popular for all children, and many Maori families keep tribal (iwi) ties alongside English surnames.","tone":2},
"om":{"boy":{"first":"Mohammed","last":"Al Balushi","say":"mo-HAM-ad al ba-LOO-shee"},
"girl":{"first":"Fatma","last":"Al Hinai","say":"FAT-ma al hi-NAA-ee"},
"about":"Omani names follow the Arabic chain: given name, then 'bin' (son of) or 'bint' (daughter of) the father, then a tribal name with 'Al'. Al Balushi marks Baluchi roots, a large community with ties across the sea in Makran. Mohammed honours the Prophet; Fatma is the local form of Fatima.","tone":3},
"pa":{"boy":{"first":"Luis","last":"González","say":"loo-EES gon-SAH-les"},
"girl":{"first":"María","last":"Rodríguez","say":"ma-REE-a rod-REE-ges"},
"about":"Panamanians use the Spanish system of two surnames: the father's first, then the mother's. González means son of Gonzalo and Rodríguez son of Rodrigo. Many families also have Afro-Caribbean, Indigenous or Chinese roots, so you will meet a wide mix of names.","tone":3},
"pe":{"boy":{"first":"Mateo","last":"Quispe","say":"ma-TAY-o KEES-pay"},
"girl":{"first":"Camila","last":"Flores","say":"ka-MEE-la FLOR-es"},
"about":"Quispe is a Quechua surname, among the most common in Peru, a sign of the country's strong Andean heritage. Flores is Spanish for flowers. Peruvians carry two surnames, the father's then the mother's, and Mateo (Matthew) and Camila have topped baby name lists in recent years.","tone":3},
"pg":{"boy":{"first":"Peter","last":"Kila","say":"PEE-ter KEE-la"},
"girl":{"first":"Grace","last":"Kila","say":"GRAYSS KEE-la"},
"about":"Papua New Guinea has over 800 languages, so names vary hugely by region. Most people have a Christian first name from missionary times plus a local name, and the 'surname' is often a father's or ancestor's name rather than a fixed family name passed down for generations.","tone":5},
"ph":{"boy":{"first":"Juan","last":"dela Cruz","say":"HWAN de-la KROOS"},
"girl":{"first":"Maria","last":"Santos","say":"ma-REE-a SAN-tos"},
"about":"Juan dela Cruz is the Filipino everyman. Spanish surnames were assigned in 1849 from an official catalogue, which is why Santos, Reyes and dela Cruz are so common. Filipinos often use the mother's maiden surname as a middle name, and playful nicknames like Bong or Jun are everywhere.","tone":3},
"pk":{"boy":{"first":"Muhammad","last":"Khan","say":"moo-HAM-mad KAAN"},
"girl":{"first":"Ayesha","last":"Ali","say":"AA-ye-sha AH-lee"},
"about":"Muhammad is the most common boy's name, honouring the Prophet; Ayesha was one of his wives. Khan is a title of rulers in Central Asia, now a surname used widely, especially among Pashtuns. Surnames are flexible in Pakistan: many people take a father's name, a clan, or a caste name.","tone":3},
"pl":{"boy":{"first":"Jakub","last":"Nowak","say":"YA-koob NO-vak"},
"girl":{"first":"Zuzanna","last":"Kowalska","say":"zoo-ZAN-na ko-VAL-ska"},
"about":"Nowak, the most common Polish surname, means newcomer. Kowalski comes from kowal, a blacksmith, and like other -ski names it changes to -ska for women. Poles also celebrate name days, the feast of the saint they are named after, sometimes as much as birthdays.","tone":1},
"ps":{"boy":{"first":"Mohammed","last":"Saleh","say":"mo-HAM-ad SAA-leh"},
"girl":{"first":"Mariam","last":"Saleh","say":"MAR-yam SAA-leh"},
"about":"Palestinian names follow the Arabic pattern of given name, father's name, grandfather's name, then a family (hamula) name. Saleh means righteous. Mariam is the Arabic form of Mary, honoured by both Muslims and Christians. Parents are often called by their eldest son's name, as in Abu Mohammed.","tone":2},
"pt":{"boy":{"first":"Francisco","last":"Silva","say":"fran-SEESH-koo SEEL-va"},
"girl":{"first":"Maria","last":"Ferreira","say":"ma-REE-a fe-RAY-ra"},
"about":"Portuguese children usually get two or more surnames, with the mother's placed before the father's, the reverse of Spain, and the last one is used day to day. Silva comes from the Latin for woodland, Ferreira from ferreiro, a smith. First names must come from an official approved list.","tone":2},
"pw":{"boy":{"first":"Joseph","last":"Ngiraked","say":"JO-sef ngee-RAA-ked"},
"girl":{"first":"Maria","last":"Tellei","say":"ma-REE-a tel-LAY"},
"about":"Palauans often pair an English or Christian first name with a Palauan surname. Many Palauan names begin with Ngira-, a common prefix in men's names. Palau's society is matrilineal: clan membership, land and titles pass through the mother's line.","tone":4},
"py":{"boy":{"first":"Mateo","last":"González","say":"ma-TAY-o gon-SAH-les"},
"girl":{"first":"Sofía","last":"Benítez","say":"so-FEE-a be-NEE-tes"},
"about":"Paraguayans use two Spanish surnames, father's first then mother's. González means son of Gonzalo and Benítez son of Benito. Most people also speak Guaraní, an Indigenous language, so you may hear warm Guaraní nicknames even though official names are Spanish.","tone":3},
"qa":{"boy":{"first":"Hamad","last":"Al Marri","say":"HA-mad al MAR-ree"},
"girl":{"first":"Maryam","last":"Al Kuwari","say":"MAR-yam al koo-WAA-ree"},
"about":"Qatari names show tribe and lineage: given name, father's name, grandfather's name, then a tribal name with 'Al', such as Al Marri or Al Kuwari. Hamad means praised, from the same root as Muhammad. Maryam is the Arabic form of Mary, mother of Jesus.","tone":3},
"ro":{"boy":{"first":"Andrei","last":"Popescu","say":"an-DRAY po-PES-koo"},
"girl":{"first":"Maria","last":"Popa","say":"ma-REE-a PO-pa"},
"about":"Popescu combines popa, an Orthodox priest, with the suffix -escu, meaning belonging to or son of, so it means the priest's family. Many Romanian surnames end in -escu or -eanu. Andrei honours Saint Andrew, the patron saint of Romania, whose feast on 30 November is a national holiday.","tone":1},
"rs":{"boy":{"first":"Luka","last":"Jovanović","say":"LOO-ka yo-VAH-no-vich"},
"girl":{"first":"Milica","last":"Petrović","say":"MEE-lee-tsa PEH-tro-vich"},
"about":"The ending -ić marks a descendant, so Jovanović means son of Jovan (John) and Petrović son of Petar. Serbian is written in both Cyrillic and Latin scripts. Many families celebrate a slava, the feast of their patron saint, inherited down the male line.","tone":1},
"ru":{"boy":{"first":"Aleksandr","last":"Ivanov","say":"a-lek-SANDR ee-va-NOF"},
"girl":{"first":"Anastasia","last":"Smirnova","say":"a-na-sta-SEE-ya SMEER-no-va"},
"about":"Every Russian has a patronymic from the father's name, like Aleksandrovich (son of Aleksandr), used with the first name as a polite form of address. Surnames take a feminine -a ending. Ivanov means son of Ivan; Smirnov likely comes from smirny, meaning meek or quiet.","tone":1},
"rw":{"boy":{"first":"Eric","last":"Habimana","say":"ER-ik ha-bee-MAA-na"},
"girl":{"first":"Aline","last":"Uwase","say":"a-LEEN oo-WAA-say"},
"about":"Rwandans traditionally have no shared family name: each child receives a personal Kinyarwanda name at a naming ceremony, often with a meaning about God or the family's hopes, so siblings have different 'surnames'. Habimana means roughly 'God exists'. A French or Christian first name is usually added.","tone":5},
"sa":{"boy":{"first":"Abdullah","last":"Al Qahtani","say":"ab-DUL-la al qah-TAA-nee"},
"girl":{"first":"Noura","last":"Al Otaibi","say":"NOO-ra al o-TAY-bee"},
"about":"Saudi names chain together given name, father's and grandfather's names (with bin or bint) and a tribal name. Al Qahtani and Al Otaibi belong to large Arabian tribes. Abdullah means servant of God, and Noura means light; women keep their own family name after marriage.","tone":3},
"sb":{"boy":{"first":"John","last":"Wale","say":"JON WAA-lay"},
"girl":{"first":"Mary","last":"Wale","say":"MAIR-ee WAA-lay"},
"about":"Solomon Islanders speak around 70 languages, so names vary by island. Most people carry a Christian first name from the mission era, and surnames are often a father's or grandfather's local name. Clan ties and, on some islands, inheritance through the mother's line remain important.","tone":5},
"sc":{"boy":{"first":"Jean","last":"Hoareau","say":"ZHON o-ROH"},
"girl":{"first":"Marie","last":"Payet","say":"ma-REE pa-YAY"},
"about":"Seychellois names reflect French settlement: surnames like Hoareau and Payet arrived with settlers from Reunion and France. Everyday life runs in Seychellois Creole, English and French, and families blend African, European, Indian and Chinese roots.","tone":4},
"sd":{"boy":{"first":"Mohamed","last":"Ahmed","say":"mo-HAM-ed AH-med"},
"girl":{"first":"Fatima","last":"Osman","say":"FAA-ti-ma os-MAAN"},
"about":"Sudanese names are usually a chain rather than a fixed surname: your own name, then your father's, then your grandfather's. So Mohamed Ahmed is Mohamed, son of Ahmed. Fatima was the Prophet's daughter, and Osman is the local form of Uthman, an early caliph.","tone":5},
"se":{"boy":{"first":"Lucas","last":"Johansson","say":"LOO-kas YOO-han-son"},
"girl":{"first":"Alice","last":"Andersson","say":"a-LEES AN-der-son"},
"about":"Johansson (son of Johan) and Andersson (son of Anders) were once true patronymics that changed every generation; they became fixed family names around 1900. Because so many Swedes shared them, families were encouraged to adopt new nature-inspired names like Lindqvist.","tone":1},
"sg":{"boy":{"first":"Wei Jie","last":"Tan","say":"WAY JYEH TAN"},
"girl":{"first":"Hui Min","last":"Lim","say":"HWAY MIN LIM"},
"about":"Most Singaporeans are of Chinese descent, and locals write the family name first: Tan Wei Jie. Tan and Lim are Hokkien spellings of Chen and Lin. Many also use an English name, like Ryan Tan. Malay names use bin or binte, and Indian names often use the father's name.","tone":2},
"si":{"boy":{"first":"Luka","last":"Novak","say":"LOO-ka NO-vak"},
"girl":{"first":"Eva","last":"Horvat","say":"EH-va HOR-vat"},
"about":"Novak, the most common Slovenian surname, means newcomer. Horvat means a Croat, recalling neighbours who settled nearby. Luka (Luke) and Eva have been favourite baby names for years. Slovenian surnames generally keep the same form for men and women.","tone":1},
"sk":{"boy":{"first":"Jakub","last":"Horváth","say":"YA-koob HOR-vaat"},
"girl":{"first":"Sofia","last":"Kováčová","say":"SO-fee-a KO-vaa-cho-vaa"},
"about":"Horváth means a Croat and Kováč means a smith. Slovak women's surnames add -ová, so Mr Kováč's daughter is Kováčová. Name days, tied to the calendar of names, are celebrated with flowers and wishes.","tone":1},
"sl":{"boy":{"first":"Mohamed","last":"Kamara","say":"mo-HAM-ed ka-MAA-ra"},
"girl":{"first":"Fatmata","last":"Sesay","say":"fat-MAA-ta SE-say"},
"about":"Kamara, Sesay, Koroma and Conteh are among the most common Sierra Leonean surnames, linked to clans of peoples like the Temne and Mandinka. Fatmata is a local form of Fatima. Muslims and Christians live side by side, and many families use names from both traditions.","tone":5},
"sm":{"boy":{"first":"Francesco","last":"Gasperoni","say":"fran-CHES-ko gas-pe-RO-nee"},
"girl":{"first":"Giulia","last":"Giardi","say":"JOO-lya JAR-dee"},
"about":"San Marino, one of the world's oldest republics, uses Italian names, but a few surnames like Gasperoni are especially common among its old families. Francesco honours Saint Francis of Assisi, Italy's patron saint, and Giulia is a favourite Italian girl's name.","tone":1},
"sn":{"boy":{"first":"Mamadou","last":"Diop","say":"MA-ma-doo JOP"},
"girl":{"first":"Aminata","last":"Ndiaye","say":"a-mee-NA-ta n-JAI"},
"about":"Mamadou is a West African form of Muhammad, and Aminata comes from Amina, the Prophet's mother. Diop and Ndiaye are classic Wolof family names, and some surnames are linked by joking kinship: people with paired names tease each other playfully. Babies are named at a ceremony a week after birth.","tone":5},
"so":{"boy":{"first":"Mohamed","last":"Abdi","say":"mo-HAM-ed AB-dee"},
"girl":{"first":"Fadumo","last":"Ahmed","say":"fa-DOO-mo AH-med"},
"about":"Somalis do not use family surnames. A person's name is their own name, then their father's, then their grandfather's, so the 'surname' Abdi is simply the father. Many Somalis can recite their paternal line back many generations, which shows their clan. Fadumo is the Somali form of Fatima.","tone":5},
"sr":{"boy":{"first":"Ravi","last":"Ramdin","say":"RAA-vee ram-DEEN"},
"girl":{"first":"Shanaya","last":"Pinas","say":"sha-NAI-ya PEE-nas"},
"about":"Suriname is one of the most diverse countries anywhere: Hindustani, Creole, Maroon, Javanese, Chinese and Indigenous families all shape its names. Ramdin is a typical Hindustani name, while Pinas is common among Creole families. Dutch is the official language.","tone":3},
"ss":{"boy":{"first":"John","last":"Deng","say":"JON DENG"},
"girl":{"first":"Achol","last":"Garang","say":"A-chol GA-rang"},
"about":"Among the Dinka, the largest group, a child's 'surname' is usually the father's name. Deng is also the name of a Dinka sky and rain deity. Names often mark birth order or the circumstances of birth, and many people also have a Christian name like John.","tone":5},
"st":{"boy":{"first":"João","last":"Costa","say":"zhoo-OW KOSH-ta"},
"girl":{"first":"Ana","last":"Pina","say":"A-na PEE-na"},
"about":"Sao Tome and Principe was settled by the Portuguese, so names follow Portuguese style, with Christian first names and surnames such as Costa (coast) and Pina. Children may carry more than one surname. Everyday speech mixes Portuguese with local creoles like Forro.","tone":4},
"sv":{"boy":{"first":"José","last":"Hernández","say":"ho-SAY er-NAN-des"},
"girl":{"first":"Ana","last":"López","say":"A-na LO-pes"},
"about":"Salvadorans have two surnames, father's first then mother's. Hernández (son of Hernando) is the country's most common surname, and López means son of Lope. José, honouring Saint Joseph, is often paired in double names like José Luis.","tone":3},
"sy":{"boy":{"first":"Mohammad","last":"Haddad","say":"mo-HAM-mad had-DAAD"},
"girl":{"first":"Sara","last":"Khalil","say":"SAA-ra kha-LEEL"},
"about":"Haddad means blacksmith in Arabic and is shared by Muslim and Christian families across the Levant. Khalil means close friend. Syrian names follow the Arabic chain of given name, father's name and family name, and parents are often called after their first son, as in Abu Mohammad.","tone":2},
"sz":{"boy":{"first":"Sibusiso","last":"Dlamini","say":"see-boo-SEE-so dla-MEE-nee"},
"girl":{"first":"Nomvula","last":"Simelane","say":"nom-VOO-la see-meh-LAH-neh"},
"about":"Dlamini is the royal clan of Eswatini and by far the most common surname. Swazi surnames are clan names, and people are often greeted by their clan praise name as a mark of respect. Sibusiso means blessing, and Nomvula is linked to rain, seen as a blessing.","tone":5},
"td":{"boy":{"first":"Mahamat","last":"Abakar","say":"ma-HA-mat a-BA-kar"},
"girl":{"first":"Fatimé","last":"Mahamat","say":"fa-tee-MAY ma-HA-mat"},
"about":"Mahamat is the Chadian form of Muhammad, and Abakar of Abu Bakr. In Chad, the second name is usually the father's given name rather than an inherited surname, so a daughter of Mahamat is Fatimé Mahamat. French and Arabic spellings both appear.","tone":5},
"tg":{"boy":{"first":"Kossi","last":"Mensah","say":"KO-see MEN-sa"},
"girl":{"first":"Afi","last":"Amouzou","say":"A-fee a-MOO-zoo"},
"about":"Many Togolese, especially Ewe speakers, receive a day name for the weekday they were born: Kossi is a boy born on Sunday. Mensah traditionally means third son. Children also get a Christian or French name, so one person may answer to several names.","tone":5},
"th":{"boy":{"first":"Thanakorn","last":"Srisuk","say":"ta-na-KORN SEE-sook"},
"girl":{"first":"Siriporn","last":"Wongsa","say":"si-ri-PORN wong-SAA"},
"about":"Thai surnames only became law in 1913, and each family had to create a unique one, so they are long and rarely shared. Almost everyone goes by a short nickname like Nok (bird) or Ploy (gem). Formal address uses the first name with Khun, never the surname.","tone":3},
"tj":{"boy":{"first":"Muhammad","last":"Rahimov","say":"moo-HAM-mad ra-HEE-mov"},
"girl":{"first":"Sitora","last":"Rahimova","say":"see-to-RAA ra-HEE-mo-va"},
"about":"Sitora means star in Tajik. Soviet-era surnames ended in Russian -ov or -ova, added to a father's or ancestor's name; Rahimov comes from Rahim, merciful. In recent years the government has pushed Persian-style names without -ov, so newer forms like Rahimzoda appear.","tone":2},
"tl":{"boy":{"first":"José","last":"da Silva","say":"zho-ZAY da SEEL-va"},
"girl":{"first":"Maria","last":"Soares","say":"ma-REE-a SWAR-esh"},
"about":"Centuries of Portuguese rule and a strongly Catholic culture mean most Timorese have Portuguese names, often several, like José da Silva. Many also have a Tetum or other local name used within the family. Surnames may come from either parent.","tone":4},
"tm":{"boy":{"first":"Merdan","last":"Orazov","say":"mer-DAN o-RAA-zov"},
"girl":{"first":"Aýgül","last":"Orazova","say":"ai-GUL o-RAA-zo-va"},
"about":"Aýgül joins aý (moon) and gül (flower). Turkmen surnames usually add the Russian ending -ov (or -ova for women) to a father's or grandfather's name, so Orazov comes from Oraz. Elders often name babies, and names may reflect hopes for strength or beauty.","tone":2},
"tn":{"boy":{"first":"Youssef","last":"Trabelsi","say":"YOO-sef tra-BEL-see"},
"girl":{"first":"Yasmine","last":"Ben Salah","say":"yas-MEEN ben sa-LAAH"},
"about":"Trabelsi means from Tripoli, one of many Tunisian surnames showing a family's place of origin. Names with Ben, meaning son of, come from an ancestor's name. Youssef is Joseph, and Yasmine comes from jasmine, a flower beloved in Tunisia.","tone":3},
"to":{"boy":{"first":"Sione","last":"Taufa","say":"see-O-nay TAU-fa"},
"girl":{"first":"Mele","last":"Fifita","say":"MEH-leh fee-FEE-ta"},
"about":"Sione (John) and Mele (Mary) are Tongan forms of Bible names brought by missionaries. Fixed surnames are fairly recent; many families took a father's or ancestor's first name as their surname. Noble titles and family rank still carry great weight in Tongan society.","tone":4},
"tr":{"boy":{"first":"Yusuf","last":"Yılmaz","say":"YOO-soof yil-MAZ"},
"girl":{"first":"Zeynep","last":"Kaya","say":"zay-NEP ka-YA"},
"about":"Turks had no surnames until a 1934 law required every family to choose one. Many picked strong, simple words: Yılmaz means one who never gives up, and Kaya means rock. Yusuf is Joseph, and Zeynep, from Zaynab, has been a top girl's name for decades.","tone":2},
"tt":{"boy":{"first":"Ryan","last":"Ali","say":"RY-an AH-lee"},
"girl":{"first":"Aaliyah","last":"Mohammed","say":"a-LEE-ya mo-HAM-ed"},
"about":"Trinidad and Tobago is a blend of Indian, African, European, Chinese and Syrian heritage. Many Indo-Trinidadian families are Muslim or Hindu, which is why Ali and Mohammed are among the most common surnames, often paired with English first names.","tone":3},
"tv":{"boy":{"first":"Ioane","last":"Taafaki","say":"ee-o-AA-nay taa-a-FAA-kee"},
"girl":{"first":"Losa","last":"Taafaki","say":"LO-sa taa-a-FAA-kee"},
"about":"Ioane is the Tuvaluan form of John, brought by Christian missionaries. Tuvaluans often use a father's name as a surname, so it can change across generations. With only about 11,000 people, nearly everyone is connected through family ties across its nine islands.","tone":4},
"tw":{"boy":{"first":"Chia-hao","last":"Chen","say":"jya-HOW CHEN"},
"girl":{"first":"Yi-chen","last":"Lin","say":"ee-CHEN LIN"},
"about":"Chen and Lin are Taiwan's most common surnames, and locals write the family name first: Chen Chia-hao. Given names are usually two characters chosen for meaning and sound, and Taiwan often uses older Wade-Giles style spellings. Many young people also choose an English name.","tone":2},
"tz":{"boy":{"first":"Baraka","last":"Juma","say":"ba-RAA-ka JOO-ma"},
"girl":{"first":"Neema","last":"Hassan","say":"neh-EH-ma HAS-san"},
"about":"Baraka means blessing and Neema means grace in Swahili. Juma, from the Arabic for Friday, is a common name and surname. Many Tanzanians take their father's first name as a surname, so it changes each generation, while others keep ethnic family names like Mushi.","tone":5},
"ua":{"boy":{"first":"Maksym","last":"Melnyk","say":"mak-SIM MEL-nik"},
"girl":{"first":"Sofiia","last":"Shevchenko","say":"so-FEE-ya shev-CHEN-ko"},
"about":"Melnyk means miller. The -enko ending means descendant of, so Shevchenko traces back to a shvets, a shoemaker; it is also the name of Taras Shevchenko, the national poet. Like Russians, Ukrainians use a patronymic from the father's name in formal address.","tone":1},
"ug":{"boy":{"first":"Brian","last":"Mugisha","say":"BRY-an moo-GEE-sha"},
"girl":{"first":"Sharon","last":"Nakato","say":"SHA-ron na-KA-to"},
"about":"Ugandans usually pair an English first name with a local name, and siblings often have different 'surnames'. Mugisha means blessing in Runyankore. Among the Baganda, Babirye and Nakato are the names given to twin girls, the first and second born.","tone":5},
"us":{"boy":{"first":"Liam","last":"Smith","say":"LEE-um SMITH"},
"girl":{"first":"Olivia","last":"Johnson","say":"o-LIV-ee-a JON-sun"},
"about":"Smith, once the name for a metalworker, and Johnson, son of John, are the two most common US surnames. Liam (from Irish William) and Olivia topped baby name charts for years. Americans come from everywhere, so Garcia, Nguyen and Kim are also very common.","tone":3},
"uy":{"boy":{"first":"Mateo","last":"Rodríguez","say":"ma-TAY-o rod-REE-ges"},
"girl":{"first":"Sofía","last":"González","say":"so-FEE-a gon-SAH-les"},
"about":"Uruguayans carry two surnames, father's then mother's. Rodríguez (son of Rodrigo) and González (son of Gonzalo) lead the list. Most Uruguayans descend from Spanish and Italian immigrants, so Italian surnames are also very common.","tone":2},
"uz":{"boy":{"first":"Jasur","last":"Karimov","say":"ja-SOOR ka-REE-mov"},
"girl":{"first":"Madina","last":"Yusupova","say":"ma-DEE-na yoo-SOO-po-va"},
"about":"Jasur means brave. Madina is named after the holy city of Medina. Uzbek surnames usually add the Russian ending -ov or -ova to an ancestor's name: Karimov from Karim (generous) and Yusupova from Yusuf (Joseph). Some families now use Uzbek-style endings instead.","tone":2},
"va":{"boy":{"first":"Francesco","last":"Rossi","say":"fran-CHES-ko ROS-see"},
"girl":{"first":"Giulia","last":"Bianchi","say":"JOO-lya bee-AN-kee"},
"about":"Hardly anyone is born in Vatican City: it has no maternity ward, and citizenship comes with a job such as cardinal or Swiss Guard, not birth. Its residents mostly carry Italian names like Rossi (red, maybe for red hair) and Bianchi (white). Francesco honours Saint Francis.","tone":1},
"vc":{"boy":{"first":"Jayden","last":"John","say":"JAY-den JON"},
"girl":{"first":"Shanelle","last":"Williams","say":"sha-NEL WIL-yumz"},
"about":"Vincentians carry English surnames, many inherited from the colonial era, such as John, Williams and Browne. Creative modern first names are popular. The islands also have Garifuna, Indian and Portuguese heritage, reflected in some family names.","tone":5},
"ve":{"boy":{"first":"Santiago","last":"González","say":"san-tee-AH-go gon-SAH-les"},
"girl":{"first":"Valentina","last":"Rodríguez","say":"va-len-TEE-na rod-REE-ges"},
"about":"Venezuelans use two surnames, father's first then mother's. González and Rodríguez are the most common. Venezuelans are famous for inventive first names, from blends of parents' names to names inspired by celebrities, alongside classics like Santiago (Saint James).","tone":3},
"vn":{"boy":{"first":"Minh","last":"Nguyễn","say":"MING NWEN"},
"girl":{"first":"Linh","last":"Trần","say":"LING CHUN"},
"about":"Locals write the family name first: Nguyễn Văn Minh. About four in ten Vietnamese are Nguyễn, a name once linked to a ruling dynasty. People are called by their given name, the last part, even formally. Minh means bright, and a middle name often marks gender.","tone":2},
"vu":{"boy":{"first":"John","last":"Tari","say":"JON TAA-ree"},
"girl":{"first":"Mary","last":"Kalo","say":"MAIR-ee KAA-lo"},
"about":"Vanuatu has over 100 languages, the most per person of any country, so names vary from island to island. Most ni-Vanuatu have a Christian first name and a local name. On some islands, names are passed down by custom and carry rights to land and status.","tone":5},
"ws":{"boy":{"first":"Ioane","last":"Leota","say":"ee-o-AA-nay le-O-ta"},
"girl":{"first":"Malia","last":"Faleolo","say":"MA-lee-a fa-le-O-lo"},
"about":"Ioane (John) and Malia (Mary) are Samoan forms of Bible names. Samoan society is built on the fa'amatai system, where extended families choose chiefs who hold matai titles. Those titles are often used before a person's name, and some families took a title or ancestor's name as their surname.","tone":4},
"xk":{"boy":{"first":"Arbër","last":"Krasniqi","say":"AR-ber kras-NEE-chee"},
"girl":{"first":"Rina","last":"Gashi","say":"REE-na GA-shee"},
"about":"Kosovo's Albanian majority often carries surnames from old highland clans, such as Krasniqi, Gashi and Berisha. Arbër comes from Arbër, an old name for Albanians, and patriotic names like it are popular. Serbian families use -ić surnames.","tone":1},
"ye":{"boy":{"first":"Mohammed","last":"Al Hakimi","say":"mo-HAM-ad al ha-KEE-mee"},
"girl":{"first":"Fatima","last":"Saleh","say":"FAA-ti-ma SAA-leh"},
"about":"Yemeni names follow the Arabic chain of given name, father's and grandfather's names, then a family or tribal name. Many surnames point to a place or tribe; Al Hakimi links to the Hakimi tribe. Fatima was the Prophet's daughter, and Saleh means righteous.","tone":3},
"za":{"boy":{"first":"Sipho","last":"Nkosi","say":"SEE-po n-KO-see"},
"girl":{"first":"Thandiwe","last":"Dlamini","say":"tan-DEE-weh dla-MEE-nee"},
"about":"Sipho means gift and Thandiwe means beloved in isiZulu. Nkosi means king or lord, and Dlamini is a large royal clan name. Many South Africans are greeted by their clan name as a sign of respect. With 12 official languages, names span Zulu, Xhosa, Afrikaans, English and more.","tone":5},
"zm":{"boy":{"first":"Joseph","last":"Banda","say":"JO-sef BAN-da"},
"girl":{"first":"Mutale","last":"Phiri","say":"moo-TAA-leh PEE-ree"},
"about":"Banda and Phiri are among the most common Zambian surnames, both clan names shared with Malawi and the Chewa and Ngoni peoples. Zambians typically pair an English first name with a name in a local language like Bemba, where Mutale is a well-loved name.","tone":5},
"zw":{"boy":{"first":"Tinashe","last":"Moyo","say":"tee-NAA-sheh MO-yo"},
"girl":{"first":"Rutendo","last":"Ncube","say":"roo-TEN-do N-koo-beh"},
"about":"Shona names often carry a message: Tinashe means God is with us, and Rutendo means faith. Moyo, meaning heart, is a totem name, and Ncube (monkey) is a common Ndebele totem. People of the same totem are seen as kin and traditionally do not marry.","tone":5}};
